from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
IR_PATH = REPO_ROOT / "src/agentic_workspace/contracts/source_decision_ir.json"
PYTHON_PATH = REPO_ROOT / "generated/workspace/python/semantic_decision.py"
TYPESCRIPT_PATH = REPO_ROOT / "generated/workspace/typescript/src/semanticDecision.mjs"

PYTHON_TEMPLATE = '''# Generated by scripts/generate/generate_source_decision.py. Do not edit.
from __future__ import annotations

import hashlib
import json
from collections.abc import Iterable, Mapping
from typing import Any

IR: dict[str, Any] = __IR__
KINDS = IR["kinds"]


class DecisionContractError(ValueError):
    """Raised when a source owner contributes an invalid decision fragment."""


def _digest(value: object) -> str:
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode()
    return "sha256:" + hashlib.sha256(encoded).hexdigest()


def _strings(value: object, *, field: str) -> list[str]:
    if value is None:
        return []
    if not isinstance(value, list) or any(not isinstance(item, str) or not item for item in value):
        raise DecisionContractError(f"{field} must be a list of non-empty strings")
    return list(value)


def _outcome(value: object, *, owner: str) -> dict[str, Any] | None:
    if value is None:
        return None
    if not isinstance(value, Mapping):
        raise DecisionContractError(f"{owner}.outcome must be an object")
    outcome = dict(value)
    for field in IR["outcome"]["required_contribution_fields"]:
        if not str(outcome.get(field) or "").strip():
            raise DecisionContractError(f"{owner}.outcome.{field} is required")
    residual_work = _strings(outcome.get("residual_work"), field=f"{owner}.outcome.residual_work")
    return {
        "id": str(outcome["id"]),
        "status": str(outcome["status"]),
        "claim": str(outcome["claim"]),
        "evidence_revision": str(outcome["evidence_revision"]),
        "residual_work": residual_work,
    }


def normalize_contribution(value: Mapping[str, Any]) -> dict[str, Any]:
    owner = str(value.get("owner") or "").strip()
    revision = str(value.get("revision") or "").strip()
    if not owner or not revision:
        raise DecisionContractError("a contribution requires owner and revision")
    for field in IR["contribution"]["rejected_legacy_fields"]:
        if field in value:
            raise DecisionContractError(f"{owner}.{field} is obsolete; use settled plus explicit outcome authority")
    blockers = value.get("blockers", [])
    actions = value.get("actions", [])
    if not isinstance(blockers, list) or any(not isinstance(item, Mapping) for item in blockers):
        raise DecisionContractError(f"{owner}.blockers must be a list of objects")
    if not isinstance(actions, list) or any(not isinstance(item, Mapping) for item in actions):
        raise DecisionContractError(f"{owner}.actions must be a list of objects")
    normalized_actions = []
    for index, raw in enumerate(actions):
        item = dict(raw)
        if "priority" in item:
            raise DecisionContractError(f"{owner}.actions[{index}].priority is obsolete; authority cannot be self-ranked")
        operation_id = str(item.get("operation_id") or "").strip()
        arguments = item.get("arguments", {})
        if not operation_id:
            raise DecisionContractError(f"{owner}.actions[{index}].operation_id is required")
        if not isinstance(arguments, Mapping):
            raise DecisionContractError(f"{owner}.actions[{index}].arguments must be an object")
        normalized_actions.append({
            "operation_id": operation_id,
            "arguments": dict(arguments),
            "effects": _strings(item.get("effects"), field=f"{owner}.actions[{index}].effects"),
            "authority": str(item.get("authority") or owner),
        })
    normalized_blockers = []
    for index, raw in enumerate(blockers):
        item = dict(raw)
        code = str(item.get("code") or "").strip()
        message = str(item.get("message") or "").strip()
        if not code or not message:
            raise DecisionContractError(f"{owner}.blockers[{index}] requires code and message")
        blocker = {"code": code, "message": message, "owner": str(item.get("owner") or owner)}
        recovery = str(item.get("recovery") or "").strip()
        if recovery:
            blocker["recovery"] = recovery
        normalized_blockers.append(blocker)
    claims = value.get("claims", {})
    facts = value.get("facts", {})
    if not isinstance(claims, Mapping):
        raise DecisionContractError(f"{owner}.claims must be an object")
    if not isinstance(facts, Mapping):
        raise DecisionContractError(f"{owner}.facts must be an object")
    return {
        "owner": owner,
        "revision": revision,
        "relevant": value.get("relevant", True) is not False,
        "settled": value.get(IR["contribution"]["local_state_field"], False) is True,
        "facts": dict(facts),
        "blockers": normalized_blockers,
        "actions": normalized_actions,
        "claims": {
            "allowed": _strings(claims.get("allowed"), field=f"{owner}.claims.allowed"),
            "blocked": _strings(claims.get("blocked"), field=f"{owner}.claims.blocked"),
        },
        "outcome": _outcome(value.get(IR["outcome"]["contribution_field"]), owner=owner),
    }


def _intent_outcome(intent: Mapping[str, Any]) -> dict[str, str] | None:
    value = intent.get(IR["outcome"]["intent_field"])
    if value is None:
        return None
    if not isinstance(value, Mapping):
        raise DecisionContractError("intent.outcome must be an object")
    result = {field: str(value.get(field) or "").strip() for field in IR["outcome"]["required_identity_fields"]}
    if any(not result[field] for field in result):
        raise DecisionContractError("intent.outcome requires id, owner, and claim")
    return result


def compile_source_decision(contributions: Iterable[Mapping[str, Any]], *, intent: Mapping[str, Any] | None = None) -> dict[str, Any]:
    current_intent = dict(intent or {})
    intended_outcome = _intent_outcome(current_intent)
    normalized = [normalize_contribution(item) for item in contributions]
    relevant = sorted((item for item in normalized if item["relevant"]), key=lambda item: item["owner"])
    owners = [item["owner"] for item in relevant]
    if len(owners) != len(set(owners)):
        raise DecisionContractError("each source owner may contribute at most once")
    source_input = {"intent": current_intent, "sources": relevant}
    input_revision = _digest(source_input)
    blockers = [blocker for item in relevant for blocker in item["blockers"]]
    actions = sorted(
        ((item["owner"], action) for item in relevant for action in item["actions"]),
        key=lambda pair: (pair[0], pair[1]["operation_id"]),
    )
    primary_action = None
    if not blockers and len(actions) == 1:
        owner, action = actions[0]
        primary_action = {
            "kind": KINDS["invocation"],
            "operation_id": action["operation_id"],
            "arguments": action["arguments"],
            "effects": action["effects"],
            "authority": action["authority"],
            "source_owner": owner,
            "expected_input_revision": input_revision,
            "idempotency_key": _digest({"operation_id": action["operation_id"], "arguments": action["arguments"], "input_revision": input_revision}),
        }
    elif not blockers and len(actions) > 1:
        blockers.append({
            "code": "multiple-actions",
            "message": "multiple current actions require an explicit dependency or authority relation",
            "owner": "operating-decision",
            "alternatives": [{"source_owner": owner, **action} for owner, action in actions],
        })
    blocked_claims = sorted({claim for item in relevant for claim in item["claims"]["blocked"]})
    allowed_claims = sorted({claim for item in relevant for claim in item["claims"]["allowed"] if claim not in blocked_claims})
    terminal_authority = None
    if intended_outcome and not blockers and not actions:
        owner_item = next((item for item in relevant if item["owner"] == intended_outcome["owner"]), None)
        outcome = owner_item["outcome"] if owner_item else None
        if (
            owner_item
            and outcome
            and outcome["id"] == intended_outcome["id"]
            and outcome["claim"] == intended_outcome["claim"]
            and outcome["status"] == IR["outcome"]["complete_status"]
            and outcome["evidence_revision"] == owner_item["revision"]
            and not outcome["residual_work"]
            and outcome["claim"] in allowed_claims
            and outcome["claim"] not in blocked_claims
        ):
            terminal_authority = {"owner": owner_item["owner"], "revision": owner_item["revision"], **outcome}
    status = "blocked" if blockers else "actionable" if primary_action else "terminal" if terminal_authority else "direct"
    answer = {
        "input_revision": input_revision,
        "status": status,
        "primary_action": primary_action,
        "blockers": blockers,
        "claim_boundary": {"allowed": allowed_claims, "blocked": blocked_claims},
        "relevant_owners": owners,
        "owner_states": [{"owner": item["owner"], "settled": item["settled"]} for item in relevant],
        "terminal_authority": terminal_authority,
    }
    return {"kind": KINDS["decision"], "decision_id": "operating-decision:" + _digest(answer).removeprefix("sha256:")[:16], **answer}


def select_decision_detail(decision: Mapping[str, Any], fields: Iterable[str]) -> dict[str, Any]:
    return {
        "kind": KINDS["decision_view"],
        "decision_id": decision.get("decision_id"),
        "input_revision": decision.get("input_revision"),
        "authoritative": False,
        "values": {field: decision[field] for field in fields if field in decision},
    }
'''

TYPESCRIPT_TEMPLATE = '''// Generated by scripts/generate/generate_source_decision.py. Do not edit.
import { createHash } from "node:crypto";

export const IR = __IR__;
const kinds = IR.kinds;
const stable = (value) => {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, stable(item)]));
  return value;
};
const digest = (value) => "sha256:" + createHash("sha256").update(JSON.stringify(stable(value))).digest("hex");
const strings = (value, field) => { if (value == null) return []; if (!Array.isArray(value) || value.some((item) => typeof item !== "string" || !item)) throw new Error(`${field} must be a list of non-empty strings`); return [...value]; };
const outcome = (value, owner) => { if (value == null) return null; if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${owner}.outcome must be an object`); for (const field of IR.outcome.required_contribution_fields) if (!String(value[field] || "").trim()) throw new Error(`${owner}.outcome.${field} is required`); return { id: String(value.id), status: String(value.status), claim: String(value.claim), evidence_revision: String(value.evidence_revision), residual_work: strings(value.residual_work, `${owner}.outcome.residual_work`) }; };

export function normalizeContribution(value) {
  const owner = String(value.owner || "").trim(); const revision = String(value.revision || "").trim();
  if (!owner || !revision) throw new Error("a contribution requires owner and revision");
  for (const field of IR.contribution.rejected_legacy_fields) if (field in value) throw new Error(`${owner}.${field} is obsolete; use settled plus explicit outcome authority`);
  const blockers = value.blockers || []; const actions = value.actions || [];
  if (!Array.isArray(blockers) || blockers.some((item) => !item || typeof item !== "object" || Array.isArray(item))) throw new Error(`${owner}.blockers must be a list of objects`);
  if (!Array.isArray(actions) || actions.some((item) => !item || typeof item !== "object" || Array.isArray(item))) throw new Error(`${owner}.actions must be a list of objects`);
  const normalizedActions = actions.map((item, index) => { if ("priority" in item) throw new Error(`${owner}.actions[${index}].priority is obsolete; authority cannot be self-ranked`); const operationId = String(item.operation_id || "").trim(); const args = item.arguments || {}; if (!operationId) throw new Error(`${owner}.actions[${index}].operation_id is required`); if (!args || typeof args !== "object" || Array.isArray(args)) throw new Error(`${owner}.actions[${index}].arguments must be an object`); return { operation_id: operationId, arguments: args, effects: strings(item.effects, `${owner}.actions[${index}].effects`), authority: String(item.authority || owner) }; });
  const normalizedBlockers = blockers.map((item, index) => { if (!item.code || !item.message) throw new Error(`${owner}.blockers[${index}] requires code and message`); return { code: String(item.code), message: String(item.message), owner: String(item.owner || owner), ...(item.recovery ? { recovery: String(item.recovery) } : {}) }; });
  const claims = value.claims || {}; const facts = value.facts || {};
  if (!claims || typeof claims !== "object" || Array.isArray(claims)) throw new Error(`${owner}.claims must be an object`);
  if (!facts || typeof facts !== "object" || Array.isArray(facts)) throw new Error(`${owner}.facts must be an object`);
  return { owner, revision, relevant: value.relevant !== false, settled: value[IR.contribution.local_state_field] === true, facts, blockers: normalizedBlockers, actions: normalizedActions, claims: { allowed: strings(claims.allowed, `${owner}.claims.allowed`), blocked: strings(claims.blocked, `${owner}.claims.blocked`) }, outcome: outcome(value[IR.outcome.contribution_field], owner) };
}

export function compileSourceDecision(contributions, intent = {}) {
  const intendedValue = intent[IR.outcome.intent_field]; let intended = null;
  if (intendedValue != null) { if (!intendedValue || typeof intendedValue !== "object" || Array.isArray(intendedValue)) throw new Error("intent.outcome must be an object"); intended = Object.fromEntries(IR.outcome.required_identity_fields.map((field) => [field, String(intendedValue[field] || "").trim()])); if (Object.values(intended).some((value) => !value)) throw new Error("intent.outcome requires id, owner, and claim"); }
  const relevant = contributions.map(normalizeContribution).filter((item) => item.relevant).sort((a, b) => a.owner.localeCompare(b.owner)); const owners = relevant.map((item) => item.owner); if (new Set(owners).size !== owners.length) throw new Error("each source owner may contribute at most once");
  const inputRevision = digest({ intent, sources: relevant }); const blockers = relevant.flatMap((item) => item.blockers); const actions = relevant.flatMap((item) => item.actions.map((action) => [item.owner, action])).sort((a, b) => a[0].localeCompare(b[0]) || a[1].operation_id.localeCompare(b[1].operation_id)); let primaryAction = null;
  if (!blockers.length && actions.length === 1) { const [owner, action] = actions[0]; primaryAction = { kind: kinds.invocation, operation_id: action.operation_id, arguments: action.arguments, effects: action.effects, authority: action.authority, source_owner: owner, expected_input_revision: inputRevision, idempotency_key: digest({ operation_id: action.operation_id, arguments: action.arguments, input_revision: inputRevision }) }; }
  else if (!blockers.length && actions.length > 1) blockers.push({ code: "multiple-actions", message: "multiple current actions require an explicit dependency or authority relation", owner: "operating-decision", alternatives: actions.map(([owner, action]) => ({ source_owner: owner, ...action })) });
  const blocked = [...new Set(relevant.flatMap((item) => item.claims.blocked))].sort(); const allowed = [...new Set(relevant.flatMap((item) => item.claims.allowed))].filter((claim) => !blocked.includes(claim)).sort(); let terminalAuthority = null;
  if (intended && !blockers.length && !actions.length) { const item = relevant.find((candidate) => candidate.owner === intended.owner); const found = item?.outcome; if (item && found && found.id === intended.id && found.claim === intended.claim && found.status === IR.outcome.complete_status && found.evidence_revision === item.revision && !found.residual_work.length && allowed.includes(found.claim) && !blocked.includes(found.claim)) terminalAuthority = { owner: item.owner, revision: item.revision, ...found }; }
  const status = blockers.length ? "blocked" : primaryAction ? "actionable" : terminalAuthority ? "terminal" : "direct"; const answer = { input_revision: inputRevision, status, primary_action: primaryAction, blockers, claim_boundary: { allowed, blocked }, relevant_owners: owners, owner_states: relevant.map((item) => ({ owner: item.owner, settled: item.settled })), terminal_authority: terminalAuthority }; return { kind: kinds.decision, decision_id: "operating-decision:" + digest(answer).slice(7, 23), ...answer };
}

export function selectDecisionDetail(decision, fields) { return { kind: kinds.decision_view, decision_id: decision.decision_id, input_revision: decision.input_revision, authoritative: false, values: Object.fromEntries(fields.filter((field) => field in decision).map((field) => [field, decision[field]])) }; }
'''


def _render(template: str, ir: dict[str, object]) -> str:
    return template.replace("__IR__", json.dumps(ir, sort_keys=True, separators=(",", ":"))).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    ir = json.loads(IR_PATH.read_text(encoding="utf-8"))
    outputs = {
        PYTHON_PATH: _render(PYTHON_TEMPLATE, ir),
        TYPESCRIPT_PATH: _render(TYPESCRIPT_TEMPLATE, ir),
    }
    stale = [path for path, content in outputs.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]
    if args.check:
        if stale:
            print("stale generated source-decision projections: " + ", ".join(str(path.relative_to(REPO_ROOT)) for path in stale))
            return 1
        return 0
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
