from __future__ import annotations

import argparse
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
IR_PATH = REPO_ROOT / "src/agentic_workspace/contracts/source_decision_ir.json"
PYTHON_PATH = REPO_ROOT / "generated/workspace/python/semantic_decision.py"
TYPESCRIPT_PATH = REPO_ROOT / "generated/workspace/typescript/src/semanticDecision.mjs"

PYTHON_TEMPLATE = '''# Generated by scripts/generate/generate_source_decision.py. Do not edit.
from __future__ import annotations

import hashlib
import json
from collections.abc import Iterable, Mapping
from typing import Any, cast

IR: dict[str, Any] = __IR__
KINDS = IR["kinds"]


class DecisionContractError(ValueError):
    """Raised when a source owner contributes an invalid decision fragment."""


def _digest(value: object) -> str:
    encoded = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode()
    return "sha256:" + hashlib.sha256(encoded).hexdigest()


def _strings(value: object, *, field: str) -> list[str]:
    if value is None:
        return []
    if not isinstance(value, list) or any(not isinstance(item, str) or not item for item in value):
        raise DecisionContractError(f"{field} must be a list of non-empty strings")
    return cast(list[str], list(value))


def _outcome(value: object, *, owner: str) -> dict[str, Any] | None:
    if value is None:
        return None
    if not isinstance(value, Mapping):
        raise DecisionContractError(f"{owner}.outcome must be an object")
    outcome = dict(value)
    for field in IR["outcome"]["required_contribution_fields"]:
        if not str(outcome.get(field) or "").strip():
            raise DecisionContractError(f"{owner}.outcome.{field} is required")
    residual_work = _strings(outcome.get("residual_work"), field=f"{owner}.outcome.residual_work")
    return {
        "id": str(outcome["id"]),
        "status": str(outcome["status"]),
        "claim": str(outcome["claim"]),
        "evidence_revision": str(outcome["evidence_revision"]),
        "residual_work": residual_work,
    }


def _affects(value: object, *, field: str) -> list[str]:
    affects = _strings(value, field=field)
    if not affects:
        raise DecisionContractError(f"{field} must name at least one affected consequence")
    task = IR["consequences"]["task"]
    prefixes = tuple(IR["consequences"]["prefixes"])
    if any(item != task and not item.startswith(prefixes) for item in affects):
        raise DecisionContractError(f"{field} contains an unsupported consequence identity")
    return sorted(set(affects))


def normalize_contribution(value: Mapping[str, Any]) -> dict[str, Any]:
    owner = str(value.get("owner") or "").strip()
    revision = str(value.get("revision") or "").strip()
    if not owner or not revision:
        raise DecisionContractError("a contribution requires owner and revision")
    for field in IR["contribution"]["rejected_legacy_fields"]:
        if field in value:
            raise DecisionContractError(f"{owner}.{field} is obsolete; use settled plus explicit outcome authority")
    blockers = value.get("blockers", [])
    actions = value.get("actions", [])
    decisions = value.get("decisions", [])
    if not isinstance(blockers, list) or any(not isinstance(item, Mapping) for item in blockers):
        raise DecisionContractError(f"{owner}.blockers must be a list of objects")
    if not isinstance(actions, list) or any(not isinstance(item, Mapping) for item in actions):
        raise DecisionContractError(f"{owner}.actions must be a list of objects")
    if not isinstance(decisions, list) or any(not isinstance(item, Mapping) for item in decisions):
        raise DecisionContractError(f"{owner}.decisions must be a list of objects")
    normalized_actions = []
    for index, raw in enumerate(actions):
        item = dict(cast(Mapping[str, Any], raw))
        if "priority" in item:
            raise DecisionContractError(f"{owner}.actions[{index}].priority is obsolete; authority cannot be self-ranked")
        operation_id = str(item.get("operation_id") or "").strip()
        arguments = item.get("arguments", {})
        if not operation_id:
            raise DecisionContractError(f"{owner}.actions[{index}].operation_id is required")
        if not isinstance(arguments, Mapping):
            raise DecisionContractError(f"{owner}.actions[{index}].arguments must be an object")
        action = {
            "operation_id": operation_id,
            "arguments": dict(arguments),
            "effects": _strings(item.get("effects"), field=f"{owner}.actions[{index}].effects"),
            "authority": str(item.get("authority") or owner),
        }
        identity = {field: action[field] for field in IR["consequences"]["action_identity_fields"]}
        normalized_actions.append({"consequence_id": f"action:{owner}:{revision}:{_digest(identity)}", **action})
    normalized_blockers = []
    for index, raw in enumerate(blockers):
        item = dict(cast(Mapping[str, Any], raw))
        code = str(item.get("code") or "").strip()
        message = str(item.get("message") or "").strip()
        if not code or not message:
            raise DecisionContractError(f"{owner}.blockers[{index}] requires code and message")
        blocker = {
            "code": code,
            "message": message,
            "owner": str(item.get("owner") or owner),
            "affects": _affects(item.get(IR["consequences"]["affected_field"]), field=f"{owner}.blockers[{index}].affects"),
        }
        recovery = str(item.get("recovery") or "").strip()
        if recovery:
            blocker["recovery"] = recovery
        normalized_blockers.append(blocker)
    normalized_decisions = []
    for index, raw in enumerate(decisions):
        item = dict(cast(Mapping[str, Any], raw))
        decision_id = str(item.get("id") or "").strip()
        question = str(item.get("question") or "").strip()
        response_operation_id = str(item.get("response_operation_id") or "").strip()
        choices = item.get("choices", [])
        if not decision_id or not question or not response_operation_id:
            raise DecisionContractError(f"{owner}.decisions[{index}] requires id, question, and response_operation_id")
        if not isinstance(choices, list) or any(not isinstance(choice, Mapping) for choice in choices):
            raise DecisionContractError(f"{owner}.decisions[{index}].choices must be a list of objects")
        normalized_choices = []
        for choice_index, raw_choice in enumerate(choices):
            choice = dict(cast(Mapping[str, Any], raw_choice))
            choice_id = str(choice.get("id") or "").strip()
            label = str(choice.get("label") or "").strip()
            if not choice_id or not label:
                raise DecisionContractError(f"{owner}.decisions[{index}].choices[{choice_index}] requires id and label")
            normalized_choices.append({"id": choice_id, "label": label})
        if not normalized_choices:
            raise DecisionContractError(f"{owner}.decisions[{index}] requires bounded choices")
        normalized_decisions.append({
            "consequence_id": f"decision:{owner}:{decision_id}",
            "id": decision_id,
            "owner": owner,
            "revision": revision,
            "question": question,
            "response_operation_id": response_operation_id,
            "choices": normalized_choices,
            "affects": _affects(item.get(IR["consequences"]["affected_field"]), field=f"{owner}.decisions[{index}].affects"),
        })
    claims = value.get("claims", {})
    facts = value.get("facts", {})
    if not isinstance(claims, Mapping):
        raise DecisionContractError(f"{owner}.claims must be an object")
    if not isinstance(facts, Mapping):
        raise DecisionContractError(f"{owner}.facts must be an object")
    return {
        "owner": owner,
        "revision": revision,
        "relevant": value.get("relevant", True) is not False,
        "settled": value.get(IR["contribution"]["local_state_field"], False) is True,
        "facts": dict(facts),
        "blockers": normalized_blockers,
        "decisions": normalized_decisions,
        "actions": normalized_actions,
        "claims": {
            "allowed": _strings(claims.get("allowed"), field=f"{owner}.claims.allowed"),
            "blocked": _strings(claims.get("blocked"), field=f"{owner}.claims.blocked"),
        },
        "outcome": _outcome(value.get(IR["outcome"]["contribution_field"]), owner=owner),
    }


def _intent_outcome(intent: Mapping[str, Any]) -> dict[str, str] | None:
    value = intent.get(IR["outcome"]["intent_field"])
    if value is None:
        return None
    if not isinstance(value, Mapping):
        raise DecisionContractError("intent.outcome must be an object")
    result = {field: str(value.get(field) or "").strip() for field in IR["outcome"]["required_identity_fields"]}
    if any(not result[field] for field in result):
        raise DecisionContractError("intent.outcome requires id, owner, and claim")
    return result


def _path(value: Any, path: str) -> Any:
    current = value
    for part in path.split("."):
        if not isinstance(current, Mapping):
            return None
        current = current.get(part)
    return current


def _eval(expression: Any, environment: Mapping[str, Any]) -> Any:
    if isinstance(expression, dict):
        return {key: _eval(value, environment) for key, value in expression.items()}
    if not isinstance(expression, list):
        return expression
    operation, *arguments = expression
    if operation == "var":
        return environment.get(arguments[0])
    if operation == "ir":
        return _path(IR, arguments[0])
    if operation == "object":
        return _eval(arguments[0], environment)
    if operation == "array":
        return [_eval(value, environment) for value in arguments]
    if operation == "let":
        local = dict(environment)
        for name, value in arguments[0]:
            local[name] = _eval(value, local)
        return _eval(arguments[1], local)
    if operation == "get":
        value = _eval(arguments[0], environment)
        key = _eval(arguments[1], environment)
        if isinstance(value, Mapping):
            return value.get(key)
        if isinstance(value, list) and isinstance(key, int) and 0 <= key < len(value):
            return value[key]
        return None
    if operation in {"map", "filter", "flat_map", "find", "any"}:
        values = list(_eval(arguments[0], environment))
        name, body = arguments[1], arguments[2]
        evaluated = [(_eval(body, {**environment, name: value}), value) for value in values]
        if operation == "map":
            return [result for result, _ in evaluated]
        if operation == "filter":
            return [value for result, value in evaluated if result]
        if operation == "flat_map":
            return [nested for result, _ in evaluated for nested in result]
        if operation == "any":
            return any(result for result, _ in evaluated)
        return next((value for result, value in evaluated if result), None)
    if operation == "sort":
        values = list(_eval(arguments[0], environment))
        paths = _eval(arguments[1], environment)
        return sorted(values, key=lambda value: tuple(_path(value, path) for path in paths) if paths else value)
    if operation == "unique":
        values = list(_eval(arguments[0], environment))
        return list(dict.fromkeys(values))
    if operation == "normalize":
        return normalize_contribution(_eval(arguments[0], environment))
    if operation == "intent_outcome":
        return _intent_outcome(_eval(arguments[0], environment))
    if operation == "digest":
        return _digest(_eval(arguments[0], environment))
    if operation == "ensure":
        if not _eval(arguments[0], environment):
            raise DecisionContractError(str(_eval(arguments[1], environment)))
        return _eval(arguments[2], environment) if len(arguments) > 2 else True
    if operation == "if":
        return _eval(arguments[1] if _eval(arguments[0], environment) else arguments[2], environment)
    if operation == "and":
        return all(_eval(value, environment) for value in arguments)
    if operation == "or":
        return any(_eval(value, environment) for value in arguments)
    if operation == "not":
        return not _eval(arguments[0], environment)
    if operation == "eq":
        return _eval(arguments[0], environment) == _eval(arguments[1], environment)
    if operation == "gt":
        return _eval(arguments[0], environment) > _eval(arguments[1], environment)
    if operation == "length":
        return len(_eval(arguments[0], environment))
    if operation == "contains":
        return _eval(arguments[1], environment) in _eval(arguments[0], environment)
    if operation == "fallback":
        value = _eval(arguments[0], environment)
        return value if value is not None else _eval(arguments[1], environment)
    if operation == "concat":
        return [item for value in arguments for item in _eval(value, environment)]
    if operation == "merge":
        return {key: item for value in arguments for key, item in _eval(value, environment).items()}
    if operation == "join":
        return "".join(str(_eval(value, environment)) for value in arguments)
    if operation == "slice":
        return _eval(arguments[0], environment)[arguments[1] : arguments[2]]
    raise DecisionContractError(f"unsupported portable expression operation: {operation}")


def compile_source_decision(contributions: Iterable[Mapping[str, Any]], *, intent: Mapping[str, Any] | None = None) -> dict[str, Any]:
    program = IR["executable_authority"]["compile_source_decision"]
    return cast(dict[str, Any], _eval(program, {"contributions": list(contributions), "intent": dict(intent or {})}))


def select_decision_detail(decision: Mapping[str, Any], fields: Iterable[str]) -> dict[str, Any]:
    return {
        "kind": KINDS["decision_view"],
        "decision_id": decision.get("decision_id"),
        "input_revision": decision.get("input_revision"),
        "authoritative": False,
        "values": {field: decision[field] for field in fields if field in decision},
    }
'''

TYPESCRIPT_TEMPLATE = '''// Generated by scripts/generate/generate_source_decision.py. Do not edit.
import { createHash } from "node:crypto";

export const IR = __IR__;
const kinds = IR.kinds;
const stable = (value) => {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).sort(([a], [b]) => a.localeCompare(b)).map(([key, item]) => [key, stable(item)]));
  return value;
};
const digest = (value) => "sha256:" + createHash("sha256").update(JSON.stringify(stable(value))).digest("hex");
const strings = (value, field) => { if (value == null) return []; if (!Array.isArray(value) || value.some((item) => typeof item !== "string" || !item)) throw new Error(`${field} must be a list of non-empty strings`); return [...value]; };
const outcome = (value, owner) => { if (value == null) return null; if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${owner}.outcome must be an object`); for (const field of IR.outcome.required_contribution_fields) if (!String(value[field] || "").trim()) throw new Error(`${owner}.outcome.${field} is required`); return { id: String(value.id), status: String(value.status), claim: String(value.claim), evidence_revision: String(value.evidence_revision), residual_work: strings(value.residual_work, `${owner}.outcome.residual_work`) }; };
const affects = (value, field) => { const result = strings(value, field); if (!result.length) throw new Error(`${field} must name at least one affected consequence`); if (result.some((item) => item !== IR.consequences.task && !IR.consequences.prefixes.some((prefix) => item.startsWith(prefix)))) throw new Error(`${field} contains an unsupported consequence identity`); return [...new Set(result)].sort(); };

export function normalizeContribution(value) {
  const owner = String(value.owner || "").trim(); const revision = String(value.revision || "").trim();
  if (!owner || !revision) throw new Error("a contribution requires owner and revision");
  for (const field of IR.contribution.rejected_legacy_fields) if (field in value) throw new Error(`${owner}.${field} is obsolete; use settled plus explicit outcome authority`);
  const blockers = value.blockers || []; const actions = value.actions || []; const decisions = value.decisions || [];
  if (!Array.isArray(blockers) || blockers.some((item) => !item || typeof item !== "object" || Array.isArray(item))) throw new Error(`${owner}.blockers must be a list of objects`);
  if (!Array.isArray(actions) || actions.some((item) => !item || typeof item !== "object" || Array.isArray(item))) throw new Error(`${owner}.actions must be a list of objects`);
  if (!Array.isArray(decisions) || decisions.some((item) => !item || typeof item !== "object" || Array.isArray(item))) throw new Error(`${owner}.decisions must be a list of objects`);
  const normalizedActions = actions.map((item, index) => { if ("priority" in item) throw new Error(`${owner}.actions[${index}].priority is obsolete; authority cannot be self-ranked`); const operationId = String(item.operation_id || "").trim(); const args = item.arguments || {}; if (!operationId) throw new Error(`${owner}.actions[${index}].operation_id is required`); if (!args || typeof args !== "object" || Array.isArray(args)) throw new Error(`${owner}.actions[${index}].arguments must be an object`); const action = { operation_id: operationId, arguments: args, effects: strings(item.effects, `${owner}.actions[${index}].effects`), authority: String(item.authority || owner) }; const identity = Object.fromEntries(IR.consequences.action_identity_fields.map((field) => [field, action[field]])); return { consequence_id: `action:${owner}:${revision}:${digest(identity)}`, ...action }; });
  const normalizedBlockers = blockers.map((item, index) => { if (!item.code || !item.message) throw new Error(`${owner}.blockers[${index}] requires code and message`); return { code: String(item.code), message: String(item.message), owner: String(item.owner || owner), affects: affects(item[IR.consequences.affected_field], `${owner}.blockers[${index}].affects`), ...(item.recovery ? { recovery: String(item.recovery) } : {}) }; });
  const normalizedDecisions = decisions.map((item, index) => { const id = String(item.id || "").trim(); const question = String(item.question || "").trim(); const responseOperationId = String(item.response_operation_id || "").trim(); const choices = item.choices || []; if (!id || !question || !responseOperationId) throw new Error(`${owner}.decisions[${index}] requires id, question, and response_operation_id`); if (!Array.isArray(choices) || choices.some((choice) => !choice || typeof choice !== "object" || Array.isArray(choice))) throw new Error(`${owner}.decisions[${index}].choices must be a list of objects`); const normalizedChoices = choices.map((choice, choiceIndex) => { if (!String(choice.id || "").trim() || !String(choice.label || "").trim()) throw new Error(`${owner}.decisions[${index}].choices[${choiceIndex}] requires id and label`); return { id: String(choice.id), label: String(choice.label) }; }); if (!normalizedChoices.length) throw new Error(`${owner}.decisions[${index}] requires bounded choices`); return { consequence_id: `decision:${owner}:${id}`, id, owner, revision, question, response_operation_id: responseOperationId, choices: normalizedChoices, affects: affects(item[IR.consequences.affected_field], `${owner}.decisions[${index}].affects`) }; });
  const claims = value.claims || {}; const facts = value.facts || {};
  if (!claims || typeof claims !== "object" || Array.isArray(claims)) throw new Error(`${owner}.claims must be an object`);
  if (!facts || typeof facts !== "object" || Array.isArray(facts)) throw new Error(`${owner}.facts must be an object`);
  return { owner, revision, relevant: value.relevant !== false, settled: value[IR.contribution.local_state_field] === true, facts, blockers: normalizedBlockers, decisions: normalizedDecisions, actions: normalizedActions, claims: { allowed: strings(claims.allowed, `${owner}.claims.allowed`), blocked: strings(claims.blocked, `${owner}.claims.blocked`) }, outcome: outcome(value[IR.outcome.contribution_field], owner) };
}

const pathValue = (value, path) => path.split(".").reduce((current, part) => current && typeof current === "object" ? current[part] : null, value);
const compareValues = (left, right) => String(left).localeCompare(String(right));
const intentOutcome = (intent) => {
  const value = intent[IR.outcome.intent_field];
  if (value == null) return null;
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error("intent.outcome must be an object");
  const result = Object.fromEntries(IR.outcome.required_identity_fields.map((field) => [field, String(value[field] || "").trim()]));
  if (Object.values(result).some((value) => !value)) throw new Error("intent.outcome requires id, owner, and claim");
  return result;
};
const evaluate = (expression, environment) => {
  if (!Array.isArray(expression)) {
    if (expression && typeof expression === "object") return Object.fromEntries(Object.entries(expression).map(([key, value]) => [key, evaluate(value, environment)]));
    return expression;
  }
  const [operation, ...args] = expression;
  if (operation === "var") return environment[args[0]];
  if (operation === "ir") return pathValue(IR, args[0]);
  if (operation === "object") return evaluate(args[0], environment);
  if (operation === "array") return args.map((value) => evaluate(value, environment));
  if (operation === "let") { const local = { ...environment }; for (const [name, value] of args[0]) local[name] = evaluate(value, local); return evaluate(args[1], local); }
  if (operation === "get") { const value = evaluate(args[0], environment); const key = evaluate(args[1], environment); return value != null && typeof value === "object" && key in value ? value[key] : null; }
  if (["map", "filter", "flat_map", "find", "any"].includes(operation)) {
    const values = [...evaluate(args[0], environment)]; const [name, body] = args.slice(1); const pairs = values.map((value) => [evaluate(body, { ...environment, [name]: value }), value]);
    if (operation === "map") return pairs.map(([result]) => result);
    if (operation === "filter") return pairs.filter(([result]) => result).map(([, value]) => value);
    if (operation === "flat_map") return pairs.flatMap(([result]) => result);
    if (operation === "any") return pairs.some(([result]) => result);
    return pairs.find(([result]) => result)?.[1] ?? null;
  }
  if (operation === "sort") { const values = [...evaluate(args[0], environment)]; const paths = evaluate(args[1], environment); return values.sort((left, right) => { for (const path of paths) { const order = compareValues(pathValue(left, path), pathValue(right, path)); if (order) return order; } return paths.length ? 0 : compareValues(left, right); }); }
  if (operation === "unique") return [...new Set(evaluate(args[0], environment))];
  if (operation === "normalize") return normalizeContribution(evaluate(args[0], environment));
  if (operation === "intent_outcome") return intentOutcome(evaluate(args[0], environment));
  if (operation === "digest") return digest(evaluate(args[0], environment));
  if (operation === "ensure") { if (!evaluate(args[0], environment)) throw new Error(String(evaluate(args[1], environment))); return args.length > 2 ? evaluate(args[2], environment) : true; }
  if (operation === "if") return evaluate(evaluate(args[0], environment) ? args[1] : args[2], environment);
  if (operation === "and") return args.every((value) => evaluate(value, environment));
  if (operation === "or") return args.some((value) => evaluate(value, environment));
  if (operation === "not") return !evaluate(args[0], environment);
  if (operation === "eq") return JSON.stringify(stable(evaluate(args[0], environment))) === JSON.stringify(stable(evaluate(args[1], environment)));
  if (operation === "gt") return evaluate(args[0], environment) > evaluate(args[1], environment);
  if (operation === "length") return evaluate(args[0], environment).length;
  if (operation === "contains") return evaluate(args[0], environment).includes(evaluate(args[1], environment));
  if (operation === "fallback") { const value = evaluate(args[0], environment); return value == null ? evaluate(args[1], environment) : value; }
  if (operation === "concat") return args.flatMap((value) => evaluate(value, environment));
  if (operation === "merge") return Object.assign({}, ...args.map((value) => evaluate(value, environment)));
  if (operation === "join") return args.map((value) => String(evaluate(value, environment))).join("");
  if (operation === "slice") return evaluate(args[0], environment).slice(args[1], args[2]);
  throw new Error(`unsupported portable expression operation: ${operation}`);
};

export function compileSourceDecision(contributions, intent = {}) {
  return evaluate(IR.executable_authority.compile_source_decision, { contributions: [...contributions], intent: { ...(intent || {}) } });
}

export function selectDecisionDetail(decision, fields) { return { kind: kinds.decision_view, decision_id: decision.decision_id, input_revision: decision.input_revision, authoritative: false, values: Object.fromEntries(fields.filter((field) => field in decision).map((field) => [field, decision[field]])) }; }
'''


def _render(template: str, ir: dict[str, object], *, python: bool = False) -> str:
    encoded = repr(ir) if python else json.dumps(ir, sort_keys=True, separators=(",", ":"))
    return template.replace("__IR__", encoded).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--root", type=Path, default=REPO_ROOT)
    parser.add_argument("--output-root", type=Path)
    args = parser.parse_args()
    source_root = args.root.resolve()
    output_root = (args.output_root or source_root).resolve()
    ir_path = source_root / IR_PATH.relative_to(REPO_ROOT)
    ir = json.loads(ir_path.read_text(encoding="utf-8"))
    outputs = {
        output_root / PYTHON_PATH.relative_to(REPO_ROOT): _render(PYTHON_TEMPLATE, ir, python=True),
        output_root / TYPESCRIPT_PATH.relative_to(REPO_ROOT): _render(TYPESCRIPT_TEMPLATE, ir),
    }
    stale = [path for path, content in outputs.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]
    if args.check:
        if stale:
            print("stale generated source-decision projections: " + ", ".join(str(path.relative_to(output_root)) for path in stale))
            return 1
        return 0
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
