# Generated by scripts/generate_contracts.py from contracts/semantic-ir.json. Do not edit.
from __future__ import annotations

import hashlib
import json
import unicodedata
from collections.abc import Iterable, Mapping
from typing import Any

IR: dict[str, Any] = {
    "api_version": "1.0",
    "decision": {
        "action_order": ["priority:descending", "owner:ascending", "operation_id:ascending"],
        "claim_policy": "blocked-overrides-allowed",
        "conflict_policy": "equal-top-priority-actions-block",
        "contribution_dimensions": [
            "facts",
            "resources",
            "procedures",
            "decisions",
            "blockers",
            "actions",
            "claims",
            "terminal",
        ],
        "statuses": ["direct", "actionable", "decision", "blocked", "terminal"],
    },
    "identity": {
        "additive_unknown_fields": "ignored-unless-required",
        "digest": "sha256",
        "encoding": "canonical-json-utf8-nfc-ascii-escaped",
        "numbers": "safe-integers-only",
        "object_keys": "unicode-code-point-order",
        "unknown_required_semantics": "fail-closed-with-upgrade-route",
    },
    "kinds": {
        "contribution": "agentic-workspace/module-contribution/v1",
        "decision": "agentic-workspace/operating-decision/v1",
        "decision_view": "agentic-workspace/decision-view/v1",
        "invocation": "agentic-workspace/operation-invocation/v1",
        "result": "agentic-workspace/operation-result/v1",
    },
    "module": {
        "capabilities": [
            "contribution/facts",
            "contribution/resources",
            "contribution/procedures",
            "contribution/decisions",
            "operation/typed-result",
            "operation/durable-commit",
            "state/owned-paths",
        ],
        "compatibility": "1.x",
        "optional_dimensions": ["facts", "resources", "procedures", "decisions", "operations"],
        "ownership_policy": "exclusive-owned-domain",
        "procedure_authority": "reference-only",
    },
    "operation": {
        "commit": "owner-serialized-durable-journal",
        "currentness": "exact-input-revision",
        "effect_policy": "result-may-only-narrow-declared-effects",
        "ownership": "atomic-acquire-or-explicit-transfer",
        "replay": "same-idempotency-key-and-request",
        "result_statuses": ["applied", "unchanged", "rejected"],
    },
    "operations": [
        {
            "binding": "repository.answer",
            "effects": ["repository-configuration"],
            "id": "repository.answer",
            "input": {
                "additionalProperties": False,
                "properties": {
                    "answer": {"minLength": 1, "type": "string"},
                    "rule_id": {"minLength": 1, "type": "string"},
                    "rule_revision": {"minLength": 1, "type": "string"},
                    "scope": {"enum": ["shared", "local"]},
                    "target": {"minLength": 1, "type": "string"},
                },
                "required": ["target", "rule_id", "rule_revision", "answer", "scope"],
                "type": "object",
            },
            "owner": "repository",
        },
        {
            "binding": "workspace.transfer_ownership",
            "effects": ["workspace-ownership"],
            "id": "workspace.transfer-ownership",
            "input": {
                "additionalProperties": False,
                "properties": {
                    "classification": {"enum": ["package-residue", "durable-module-state", "local-diagnostic"]},
                    "expected_sha256": {"pattern": "^sha256:[0-9a-f]{64}$", "type": "string"},
                    "from_owner": {"minLength": 1, "type": "string"},
                    "path": {"minLength": 1, "type": "string"},
                    "target": {"minLength": 1, "type": "string"},
                    "to_owner": {"minLength": 1, "type": "string"},
                },
                "required": ["target", "path", "from_owner", "to_owner", "expected_sha256", "classification"],
                "type": "object",
            },
            "owner": "workspace",
        },
        {
            "binding": "workspace.remove",
            "effects": ["workspace-managed-files"],
            "id": "workspace.remove",
            "input": {
                "additionalProperties": False,
                "properties": {"target": {"minLength": 1, "type": "string"}},
                "required": ["target"],
                "type": "object",
            },
            "owner": "workspace",
        },
        {
            "binding": "workspace.remove_legacy",
            "effects": ["workspace-managed-files"],
            "id": "workspace.remove-legacy",
            "input": {
                "additionalProperties": False,
                "properties": {"confirm": {"const": "remove-managed-v0"}, "target": {"minLength": 1, "type": "string"}},
                "required": ["target", "confirm"],
                "type": "object",
            },
            "owner": "workspace",
        },
        {
            "binding": "planning.set",
            "effects": ["planning-state"],
            "id": "planning.set",
            "input": {
                "additionalProperties": False,
                "properties": {
                    "constraints": {"items": {"type": "string"}, "type": "array"},
                    "dependencies": {"items": {"type": "string"}, "type": "array"},
                    "item": {"minLength": 1, "type": "string"},
                    "outcome": {"type": "string"},
                    "proof_claims": {"items": {"type": "string"}, "type": "array"},
                    "scope": {"items": {"type": "string"}, "type": "array"},
                    "status": {
                        "enum": [
                            "in-progress",
                            "blocked",
                            "in-flight",
                            "returned",
                            "integration-pending",
                            "residual",
                            "ready-to-complete",
                            "complete",
                        ]
                    },
                    "stops": {"items": {"type": "string"}, "type": "array"},
                    "target": {"minLength": 1, "type": "string"},
                },
                "required": ["target", "item", "status"],
                "type": "object",
            },
            "owner": "planning",
        },
        {
            "binding": "planning.reconcile",
            "effects": ["planning-state"],
            "id": "planning.reconcile",
            "input": {
                "additionalProperties": False,
                "properties": {
                    "disposition": {"enum": ["integrated", "revise-scope", "residual"]},
                    "expected_subject_revision": {"minLength": 1, "type": "string"},
                    "item": {"minLength": 1, "type": "string"},
                    "target": {"minLength": 1, "type": "string"},
                },
                "required": ["target", "item", "expected_subject_revision", "disposition"],
                "type": "object",
            },
            "owner": "planning",
        },
        {
            "binding": "planning.record_attempt",
            "effects": ["planning-state"],
            "id": "planning.record-attempt",
            "input": {
                "additionalProperties": False,
                "properties": {
                    "attempt_id": {"minLength": 1, "type": "string"},
                    "expected_subject_revision": {"minLength": 1, "type": "string"},
                    "item": {"minLength": 1, "type": "string"},
                    "result_revision": {"type": "string"},
                    "status": {"enum": ["dispatched", "in-flight", "returned", "failed"]},
                    "target": {"minLength": 1, "type": "string"},
                    "target_id": {"minLength": 1, "type": "string"},
                },
                "required": ["target", "item", "expected_subject_revision", "attempt_id", "target_id", "status"],
                "type": "object",
            },
            "owner": "planning",
        },
        {
            "binding": "planning.complete",
            "effects": ["planning-state"],
            "id": "planning.complete",
            "input": {
                "additionalProperties": False,
                "properties": {
                    "item": {"minLength": 1, "type": "string"},
                    "target": {"minLength": 1, "type": "string"},
                },
                "required": ["target", "item"],
                "type": "object",
            },
            "owner": "planning",
        },
        {
            "binding": "memory.read",
            "effects": [],
            "id": "memory.read",
            "input": {
                "additionalProperties": False,
                "properties": {"key": {"minLength": 1, "type": "string"}, "target": {"minLength": 1, "type": "string"}},
                "required": ["target", "key"],
                "type": "object",
            },
            "owner": "memory",
        },
        {
            "binding": "memory.record",
            "effects": ["memory-state"],
            "id": "memory.record",
            "input": {
                "additionalProperties": False,
                "properties": {
                    "dependency_revision": {"type": "string"},
                    "key": {"minLength": 1, "type": "string"},
                    "kind": {"enum": ["advisory", "workaround"]},
                    "paths": {"items": {"type": "string"}, "type": "array"},
                    "provenance": {"type": "string"},
                    "summary": {"type": "string"},
                    "target": {"minLength": 1, "type": "string"},
                    "task_terms": {"items": {"type": "string"}, "type": "array"},
                    "value": {},
                },
                "required": ["target", "key", "value"],
                "type": "object",
            },
            "owner": "memory",
        },
        {
            "binding": "memory.disposition",
            "effects": ["memory-state"],
            "id": "memory.disposition",
            "input": {
                "additionalProperties": False,
                "properties": {
                    "disposition": {"enum": ["active", "promoted", "retired"]},
                    "key": {"minLength": 1, "type": "string"},
                    "stronger_owner": {"type": "string"},
                    "target": {"minLength": 1, "type": "string"},
                },
                "required": ["target", "key", "disposition"],
                "type": "object",
            },
            "owner": "memory",
        },
        {
            "binding": "verification.run",
            "effects": ["verification-state", "process"],
            "id": "verification.run",
            "input": {
                "additionalProperties": False,
                "properties": {
                    "commands": {
                        "items": {"items": {"minLength": 1, "type": "string"}, "minItems": 1, "type": "array"},
                        "type": "array",
                    },
                    "route_id": {"minLength": 1, "type": "string"},
                    "strategy_revision": {"minLength": 1, "type": "string"},
                    "subject_revision": {"minLength": 1, "type": "string"},
                    "target": {"minLength": 1, "type": "string"},
                },
                "required": ["target", "subject_revision", "strategy_revision", "route_id", "commands"],
                "type": "object",
            },
            "owner": "verification",
        },
    ],
    "package_version": "1.0.0",
    "primitive_inventory": {
        "python": [
            "argparse CLI bootstrap",
            "filesystem persistence",
            "Python entry-point discovery",
            "process execution",
            "JSON Schema validation",
            "typed handler dispatch and persistence callbacks",
        ],
        "typescript": [
            "ES module bootstrap",
            "host-supplied module registration",
            "host-supplied persistence and process bindings",
            "typed handler dispatch and schema validation",
        ],
    },
    "reuse": {
        "currentness": "owner-revision-plus-exact-dependencies",
        "scope": "source-owner-conclusion",
        "transcripts": False,
        "volatile-ranking": False,
    },
    "schema_version": 1,
}
KINDS = IR["kinds"]
OPERATION_CONTRACTS = {item["id"]: item for item in IR["operations"]}


def operation_contract(operation_id: str) -> dict[str, Any]:
    try:
        return dict(OPERATION_CONTRACTS[operation_id])
    except KeyError as exc:
        raise ValueError(f"unknown generated operation contract: {operation_id}") from exc


class DecisionContractError(ValueError):
    """Raised when a source owner contributes an invalid decision fragment."""


def _canonical(value: object) -> object:
    if isinstance(value, str):
        return unicodedata.normalize("NFC", value)
    if isinstance(value, bool) or value is None or isinstance(value, int):
        return value
    if isinstance(value, float):
        raise DecisionContractError("canonical semantic numbers must be integers")
    if isinstance(value, Mapping):
        return {
            unicodedata.normalize("NFC", str(key)): _canonical(item)
            for key, item in sorted(value.items(), key=lambda pair: unicodedata.normalize("NFC", str(pair[0])))
        }
    if isinstance(value, (list, tuple)):
        return [_canonical(item) for item in value]
    raise DecisionContractError(f"unsupported canonical semantic value: {type(value).__name__}")


def canonical_serialize(value: object) -> str:
    return json.dumps(_canonical(value), sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def semantic_digest(value: object) -> str:
    encoded = canonical_serialize(value).encode("utf-8")
    return "sha256:" + hashlib.sha256(encoded).hexdigest()


_digest = semantic_digest


def owner_conclusion_identity(owner: str, revision: str, dependencies: Mapping[str, Any] | None = None) -> str:
    if not owner or not revision:
        raise DecisionContractError("owner conclusion identity requires owner and revision")
    return semantic_digest({"owner": owner, "revision": revision, "dependencies": dict(dependencies or {})})


def _strings(value: object, *, field: str) -> list[str]:
    if value is None:
        return []
    if not isinstance(value, list) or any(not isinstance(item, str) or not item for item in value):
        raise DecisionContractError(f"{field} must be a list of non-empty strings")
    return [item for item in value if isinstance(item, str)]


def _references(value: object, *, owner: str, field: str) -> list[dict[str, Any]]:
    if value is None:
        return []
    if not isinstance(value, list) or any(not isinstance(item, Mapping) for item in value):
        raise DecisionContractError(f"{owner}.{field} must be a list of objects")
    references = []
    typed = [dict(item) for item in value if isinstance(item, Mapping)]
    for index, item in enumerate(typed):
        resource_id = str(item.get("id") or "").strip()
        revision = str(item.get("revision") or "").strip()
        locator = str(item.get("locator") or "").strip()
        if not resource_id or not revision or not locator:
            raise DecisionContractError(f"{owner}.{field}[{index}] requires id, revision, and locator")
        references.append(
            {
                "id": resource_id,
                "owner": owner,
                "revision": revision,
                "locator": locator,
                "summary": str(item.get("summary") or ""),
                "authority": "reference-only" if field == "procedures" else "read-only",
            }
        )
    return references


def normalize_contribution(value: Mapping[str, Any]) -> dict[str, Any]:
    owner = str(value.get("owner") or "").strip()
    revision = str(value.get("revision") or "").strip()
    if not owner or not revision:
        raise DecisionContractError("a contribution requires owner and revision")
    blockers = value.get("blockers", [])
    actions = value.get("actions", [])
    decisions = value.get("decisions", [])
    if not isinstance(blockers, list) or any(not isinstance(item, Mapping) for item in blockers):
        raise DecisionContractError(f"{owner}.blockers must be a list of objects")
    if not isinstance(actions, list) or any(not isinstance(item, Mapping) for item in actions):
        raise DecisionContractError(f"{owner}.actions must be a list of objects")
    if not isinstance(decisions, list) or any(not isinstance(item, Mapping) for item in decisions):
        raise DecisionContractError(f"{owner}.decisions must be a list of objects")
    normalized_actions = []
    typed_actions = [dict(item) for item in actions if isinstance(item, Mapping)]
    for index, item in enumerate(typed_actions):
        operation_id = str(item.get("operation_id") or "").strip()
        arguments = item.get("arguments", {})
        priority = item.get("priority", 0)
        if not operation_id:
            raise DecisionContractError(f"{owner}.actions[{index}].operation_id is required")
        if not isinstance(arguments, Mapping):
            raise DecisionContractError(f"{owner}.actions[{index}].arguments must be an object")
        if not isinstance(priority, int):
            raise DecisionContractError(f"{owner}.actions[{index}].priority must be an integer")
        normalized_actions.append(
            {
                "operation_id": operation_id,
                "arguments": dict(arguments),
                "effects": _strings(item.get("effects"), field=f"{owner}.actions[{index}].effects"),
                "authority": str(item.get("authority") or owner),
                "priority": priority,
            }
        )
    normalized_blockers = []
    typed_blockers = [dict(item) for item in blockers if isinstance(item, Mapping)]
    for index, item in enumerate(typed_blockers):
        code = str(item.get("code") or "").strip()
        message = str(item.get("message") or "").strip()
        if not code or not message:
            raise DecisionContractError(f"{owner}.blockers[{index}] requires code and message")
        blocker = {"code": code, "message": message, "owner": str(item.get("owner") or owner)}
        recovery = str(item.get("recovery") or "").strip()
        if recovery:
            blocker["recovery"] = recovery
        normalized_blockers.append(blocker)
    normalized_decisions = []
    typed_decisions = [dict(item) for item in decisions if isinstance(item, Mapping)]
    for index, item in enumerate(typed_decisions):
        decision_id = str(item.get("id") or "").strip()
        question = str(item.get("question") or "").strip()
        authority = str(item.get("authority") or "").strip()
        response_operation_id = str(item.get("response_operation_id") or "").strip()
        choices = item.get("choices", [])
        allow_open = item.get("allow_open", False) is True
        if not decision_id or not question or not authority or not response_operation_id:
            raise DecisionContractError(
                f"{owner}.decisions[{index}] requires id, question, authority, and response_operation_id"
            )
        if not isinstance(choices, list) or any(not isinstance(choice, Mapping) for choice in choices):
            raise DecisionContractError(f"{owner}.decisions[{index}].choices must be a list of objects")
        normalized_choices = []
        typed_choices = [dict(choice) for choice in choices if isinstance(choice, Mapping)]
        for choice_index, choice in enumerate(typed_choices):
            choice_id = str(choice.get("id") or "").strip()
            label = str(choice.get("label") or "").strip()
            if not choice_id or not label:
                raise DecisionContractError(f"{owner}.decisions[{index}].choices[{choice_index}] requires id and label")
            normalized_choices.append({"id": choice_id, "label": label})
        if not normalized_choices and not allow_open:
            raise DecisionContractError(f"{owner}.decisions[{index}] requires finite choices or allow_open")
        normalized_decisions.append(
            {
                "id": decision_id,
                "owner": owner,
                "revision": revision,
                "detail_revision": str(item.get("detail_revision") or revision),
                "question": question,
                "authority": authority,
                "response_operation_id": response_operation_id,
                "effects": _strings(item.get("effects"), field=f"{owner}.decisions[{index}].effects"),
                "choices": normalized_choices,
                "allow_open": allow_open,
            }
        )
    claims = value.get("claims", {})
    facts = value.get("facts", {})
    if not isinstance(claims, Mapping):
        raise DecisionContractError(f"{owner}.claims must be an object")
    if not isinstance(facts, Mapping):
        raise DecisionContractError(f"{owner}.facts must be an object")
    return {
        "owner": owner,
        "revision": revision,
        "relevant": value.get("relevant", True) is not False,
        "facts": dict(facts),
        "resources": _references(value.get("resources"), owner=owner, field="resources"),
        "procedures": _references(value.get("procedures"), owner=owner, field="procedures"),
        "decisions": normalized_decisions,
        "blockers": normalized_blockers,
        "actions": normalized_actions,
        "claims": {
            "allowed": _strings(claims.get("allowed"), field=f"{owner}.claims.allowed"),
            "blocked": _strings(claims.get("blocked"), field=f"{owner}.claims.blocked"),
        },
        "terminal": value.get("terminal", False) is True,
    }


def compile_source_decision(
    contributions: Iterable[Mapping[str, Any]], *, intent: Mapping[str, Any] | None = None
) -> dict[str, Any]:
    normalized = [normalize_contribution(item) for item in contributions]
    relevant = sorted((item for item in normalized if item["relevant"]), key=lambda item: item["owner"])
    owners = [item["owner"] for item in relevant]
    if len(owners) != len(set(owners)):
        raise DecisionContractError("each source owner may contribute at most once")
    source_input = {"intent": dict(intent or {}), "sources": relevant}
    input_revision = _digest(source_input)
    blockers = [blocker for item in relevant for blocker in item["blockers"]]
    decisions = [decision for item in relevant for decision in item["decisions"]]
    actions = [(item["owner"], action) for item in relevant for action in item["actions"]]
    primary_action = None
    decision_request = None
    if not blockers and len(decisions) == 1:
        decision_request = decisions[0]
    elif not blockers and len(decisions) > 1:
        blockers.append(
            {
                "code": "ambiguous-decision",
                "message": "multiple source owners require a current human/domain decision",
                "owner": "operating-decision",
                "recovery": "reconcile the competing decision owners",
            }
        )
    if not blockers and decision_request is None and actions:
        actions.sort(key=lambda pair: (-pair[1]["priority"], pair[0], pair[1]["operation_id"]))
        top_priority = actions[0][1]["priority"]
        tied = [pair for pair in actions if pair[1]["priority"] == top_priority]
        if len(tied) > 1:
            blockers.append(
                {
                    "code": "ambiguous-action",
                    "message": "multiple source owners proposed equally authoritative actions",
                    "owner": "operating-decision",
                    "recovery": "reconcile the competing source owners",
                }
            )
        else:
            owner, action = actions[0]
            primary_action = {
                "kind": KINDS["invocation"],
                "operation_id": action["operation_id"],
                "arguments": action["arguments"],
                "intent": dict(intent or {}),
                "effects": action["effects"],
                "authority": action["authority"],
                "source_owner": owner,
                "expected_input_revision": input_revision,
                "idempotency_key": _digest(
                    {
                        "operation_id": action["operation_id"],
                        "arguments": action["arguments"],
                        "input_revision": input_revision,
                    }
                ),
            }
    allowed = sorted({claim for item in relevant for claim in item["claims"]["allowed"]})
    blocked = sorted({claim for item in relevant for claim in item["claims"]["blocked"]})
    allowed = [claim for claim in allowed if claim not in blocked]
    if len(blockers) > 1:
        causes = sorted(f"{item['owner']}:{item['code']}" for item in blockers)
        blockers = [
            {
                "code": "multiple-blockers",
                "message": "multiple current blockers require source-owner reconciliation",
                "owner": "operating-decision",
                "recovery": "reconcile: " + ", ".join(causes),
            }
        ]
    if blockers:
        status = "blocked"
        primary_action = None
        decision_request = None
    elif decision_request:
        status = "decision"
    elif primary_action:
        status = "actionable"
    elif relevant and all(item["terminal"] for item in relevant):
        status = "terminal"
    else:
        status = "direct"
    resources = [resource for item in relevant for resource in item["resources"]]
    procedures = [procedure for item in relevant for procedure in item["procedures"]]
    resources = list({canonical_serialize(item): item for item in resources}.values())
    procedures = list({canonical_serialize(item): item for item in procedures}.values())
    answer = {
        "input_revision": input_revision,
        "status": status,
        "primary_action": primary_action,
        "decision_request": decision_request,
        "blockers": blockers,
        "claim_boundary": {"allowed": allowed, "blocked": blocked},
        "relevant_owners": owners,
        "resources": resources,
        "procedures": procedures,
    }
    return {
        "kind": KINDS["decision"],
        "decision_id": "operating-decision:" + _digest(answer).removeprefix("sha256:")[:16],
        **answer,
    }


def select_decision_detail(decision: Mapping[str, Any], fields: Iterable[str]) -> dict[str, Any]:
    selected = {field: decision[field] for field in fields if field in decision}
    return {
        "kind": KINDS["decision_view"],
        "decision_id": decision.get("decision_id"),
        "input_revision": decision.get("input_revision"),
        "authoritative": False,
        "values": selected,
    }
