from __future__ import annotations

# ruff: noqa: E501
import argparse
import json
import pprint
import shutil
import subprocess
import tomllib
from pathlib import Path

PYTHON_TEMPLATE = '''# Generated by scripts/generate_contracts.py from contracts/semantic-ir.json. Do not edit.
from __future__ import annotations

import hashlib
import json
import unicodedata
from collections.abc import Iterable, Mapping
from typing import Any

IR: dict[str, Any] = __IR__
BUNDLED_SKILLS: dict[str, dict[str, str]] = __SKILLS__
KINDS = IR["kinds"]
OPERATION_CONTRACTS = {item["id"]: item for item in IR["operations"]}


def bundled_skill(name: str) -> dict[str, str]:
    try:
        return dict(BUNDLED_SKILLS[name])
    except KeyError as exc:
        raise ValueError(f"unknown bundled skill: {name}") from exc


def workspace_configuration_skill() -> dict[str, str]:
    return bundled_skill("workspace-configuration")


def operation_contract(operation_id: str) -> dict[str, Any]:
    try:
        return dict(OPERATION_CONTRACTS[operation_id])
    except KeyError as exc:
        raise ValueError(f"unknown generated operation contract: {operation_id}") from exc


class DecisionContractError(ValueError):
    """Raised when a source owner contributes an invalid decision fragment."""


def _canonical(value: object) -> object:
    if isinstance(value, str):
        return unicodedata.normalize("NFC", value)
    if isinstance(value, bool) or value is None or isinstance(value, int):
        return value
    if isinstance(value, float):
        raise DecisionContractError("canonical semantic numbers must be integers")
    if isinstance(value, Mapping):
        return {unicodedata.normalize("NFC", str(key)): _canonical(item) for key, item in sorted(value.items(), key=lambda pair: unicodedata.normalize("NFC", str(pair[0])))}
    if isinstance(value, (list, tuple)):
        return [_canonical(item) for item in value]
    raise DecisionContractError(f"unsupported canonical semantic value: {type(value).__name__}")


def canonical_serialize(value: object) -> str:
    return json.dumps(_canonical(value), sort_keys=True, separators=(",", ":"), ensure_ascii=True)


def semantic_digest(value: object) -> str:
    encoded = canonical_serialize(value).encode("utf-8")
    return "sha256:" + hashlib.sha256(encoded).hexdigest()


_digest = semantic_digest


def owner_conclusion_identity(owner: str, revision: str, dependencies: Mapping[str, Any] | None = None) -> str:
    if not owner or not revision:
        raise DecisionContractError("owner conclusion identity requires owner and revision")
    return semantic_digest({"owner": owner, "revision": revision, "dependencies": dict(dependencies or {})})


def _strings(value: object, *, field: str) -> list[str]:
    if value is None:
        return []
    if not isinstance(value, list) or any(not isinstance(item, str) or not item for item in value):
        raise DecisionContractError(f"{field} must be a list of non-empty strings")
    return [item for item in value if isinstance(item, str)]


def _references(value: object, *, owner: str, field: str) -> list[dict[str, Any]]:
    if value is None:
        return []
    if not isinstance(value, list) or any(not isinstance(item, Mapping) for item in value):
        raise DecisionContractError(f"{owner}.{field} must be a list of objects")
    references = []
    typed = [dict(item) for item in value if isinstance(item, Mapping)]
    for index, item in enumerate(typed):
        resource_id = str(item.get("id") or "").strip()
        revision = str(item.get("revision") or "").strip()
        locator = str(item.get("locator") or "").strip()
        if not resource_id or not revision or not locator:
            raise DecisionContractError(f"{owner}.{field}[{index}] requires id, revision, and locator")
        references.append({
            "id": resource_id,
            "owner": owner,
            "revision": revision,
            "locator": locator,
            "summary": str(item.get("summary") or ""),
            "authority": "reference-only" if field == "procedures" else "read-only",
        })
    return references


def normalize_contribution(value: Mapping[str, Any]) -> dict[str, Any]:
    owner = str(value.get("owner") or "").strip()
    revision = str(value.get("revision") or "").strip()
    if not owner or not revision:
        raise DecisionContractError("a contribution requires owner and revision")
    blockers = value.get("blockers", [])
    actions = value.get("actions", [])
    decisions = value.get("decisions", [])
    if not isinstance(blockers, list) or any(not isinstance(item, Mapping) for item in blockers):
        raise DecisionContractError(f"{owner}.blockers must be a list of objects")
    if not isinstance(actions, list) or any(not isinstance(item, Mapping) for item in actions):
        raise DecisionContractError(f"{owner}.actions must be a list of objects")
    if not isinstance(decisions, list) or any(not isinstance(item, Mapping) for item in decisions):
        raise DecisionContractError(f"{owner}.decisions must be a list of objects")
    normalized_actions = []
    typed_actions = [dict(item) for item in actions if isinstance(item, Mapping)]
    for index, item in enumerate(typed_actions):
        operation_id = str(item.get("operation_id") or "").strip()
        arguments = item.get("arguments", {})
        priority = item.get("priority", 0)
        if not operation_id:
            raise DecisionContractError(f"{owner}.actions[{index}].operation_id is required")
        if not isinstance(arguments, Mapping):
            raise DecisionContractError(f"{owner}.actions[{index}].arguments must be an object")
        if not isinstance(priority, int):
            raise DecisionContractError(f"{owner}.actions[{index}].priority must be an integer")
        normalized_actions.append({
            "operation_id": operation_id,
            "arguments": dict(arguments),
            "effects": _strings(item.get("effects"), field=f"{owner}.actions[{index}].effects"),
            "authority": str(item.get("authority") or owner),
            "source_owner": str(item.get("source_owner") or owner),
            "handoff_source": str(item.get("handoff_source") or ""),
            "priority": priority,
        })
    normalized_blockers = []
    typed_blockers = [dict(item) for item in blockers if isinstance(item, Mapping)]
    for index, item in enumerate(typed_blockers):
        code = str(item.get("code") or "").strip()
        message = str(item.get("message") or "").strip()
        if not code or not message:
            raise DecisionContractError(f"{owner}.blockers[{index}] requires code and message")
        blocker = {"code": code, "message": message, "owner": str(item.get("owner") or owner)}
        recovery = str(item.get("recovery") or "").strip()
        if recovery:
            blocker["recovery"] = recovery
        normalized_blockers.append(blocker)
    normalized_decisions = []
    typed_decisions = [dict(item) for item in decisions if isinstance(item, Mapping)]
    for index, item in enumerate(typed_decisions):
        decision_id = str(item.get("id") or "").strip()
        question = str(item.get("question") or "").strip()
        authority = str(item.get("authority") or "").strip()
        response_operation_id = str(item.get("response_operation_id") or "").strip()
        choices = item.get("choices", [])
        allow_open = item.get("allow_open", False) is True
        if not decision_id or not question or not authority or not response_operation_id:
            raise DecisionContractError(f"{owner}.decisions[{index}] requires id, question, authority, and response_operation_id")
        if not isinstance(choices, list) or any(not isinstance(choice, Mapping) for choice in choices):
            raise DecisionContractError(f"{owner}.decisions[{index}].choices must be a list of objects")
        normalized_choices = []
        typed_choices = [dict(choice) for choice in choices if isinstance(choice, Mapping)]
        for choice_index, choice in enumerate(typed_choices):
            choice_id = str(choice.get("id") or "").strip()
            label = str(choice.get("label") or "").strip()
            if not choice_id or not label:
                raise DecisionContractError(f"{owner}.decisions[{index}].choices[{choice_index}] requires id and label")
            normalized_choices.append({"id": choice_id, "label": label})
        if not normalized_choices and not allow_open:
            raise DecisionContractError(f"{owner}.decisions[{index}] requires finite choices or allow_open")
        normalized_decisions.append({
            "id": decision_id,
            "owner": owner,
            "revision": revision,
            "detail_revision": str(item.get("detail_revision") or revision),
            "question": question,
            "authority": authority,
            "response_operation_id": response_operation_id,
            "effects": _strings(item.get("effects"), field=f"{owner}.decisions[{index}].effects"),
            "choices": normalized_choices,
            "allow_open": allow_open,
        })
    claims = value.get("claims", {})
    facts = value.get("facts", {})
    if not isinstance(claims, Mapping):
        raise DecisionContractError(f"{owner}.claims must be an object")
    if not isinstance(facts, Mapping):
        raise DecisionContractError(f"{owner}.facts must be an object")
    return {
        "owner": owner,
        "revision": revision,
        "relevant": value.get("relevant", True) is not False,
        "facts": dict(facts),
        "resources": _references(value.get("resources"), owner=owner, field="resources"),
        "procedures": _references(value.get("procedures"), owner=owner, field="procedures"),
        "decisions": normalized_decisions,
        "blockers": normalized_blockers,
        "actions": normalized_actions,
        "claims": {
            "allowed": _strings(claims.get("allowed"), field=f"{owner}.claims.allowed"),
            "blocked": _strings(claims.get("blocked"), field=f"{owner}.claims.blocked"),
        },
        "terminal": value.get("terminal", False) is True,
    }


def compile_source_decision(contributions: Iterable[Mapping[str, Any]], *, intent: Mapping[str, Any] | None = None) -> dict[str, Any]:
    normalized = [normalize_contribution(item) for item in contributions]
    relevant = sorted((item for item in normalized if item["relevant"]), key=lambda item: item["owner"])
    owners = [item["owner"] for item in relevant]
    if len(owners) != len(set(owners)):
        raise DecisionContractError("each source owner may contribute at most once")
    source_input = {"intent": dict(intent or {}), "sources": relevant}
    input_revision = _digest(source_input)
    blockers = [blocker for item in relevant for blocker in item["blockers"]]
    decisions = [decision for item in relevant for decision in item["decisions"]]
    actions = [(item["owner"], action) for item in relevant for action in item["actions"]]
    primary_action = None
    decision_request = None
    if not blockers and len(decisions) == 1:
        decision_request = decisions[0]
    elif not blockers and len(decisions) > 1:
        blockers.append({
            "code": "ambiguous-decision",
            "message": "multiple source owners require a current human/domain decision",
            "owner": "operating-decision",
            "recovery": "reconcile the competing decision owners",
        })
    if not blockers and decision_request is None and actions:
        actions.sort(key=lambda pair: (-pair[1]["priority"], pair[0], pair[1]["operation_id"]))
        top_priority = actions[0][1]["priority"]
        tied = [pair for pair in actions if pair[1]["priority"] == top_priority]
        if len(tied) > 1:
            blockers.append({
                "code": "ambiguous-action",
                "message": "multiple source owners proposed equally authoritative actions",
                "owner": "operating-decision",
                "recovery": "reconcile the competing source owners",
            })
        else:
            owner, action = actions[0]
            primary_action = {
                "kind": KINDS["invocation"],
                "operation_id": action["operation_id"],
                "arguments": action["arguments"],
                "intent": dict(intent or {}),
                "effects": action["effects"],
                "authority": action["authority"],
                "source_owner": action["source_owner"],
                **({"handoff_source": action["handoff_source"]} if action["handoff_source"] else {}),
                "expected_input_revision": input_revision,
                "idempotency_key": _digest({"operation_id": action["operation_id"], "arguments": action["arguments"], "input_revision": input_revision}),
            }
    allowed = sorted({claim for item in relevant for claim in item["claims"]["allowed"]})
    blocked = sorted({claim for item in relevant for claim in item["claims"]["blocked"]})
    allowed = [claim for claim in allowed if claim not in blocked]
    if len(blockers) > 1:
        causes = sorted(f"{item['owner']}:{item['code']}" for item in blockers)
        blockers = [{
            "code": "multiple-blockers",
            "message": "multiple current blockers require source-owner reconciliation",
            "owner": "operating-decision",
            "recovery": "reconcile: " + ", ".join(causes),
        }]
    if blockers:
        status = "blocked"
        primary_action = None
        decision_request = None
    elif decision_request:
        status = "decision"
    elif primary_action:
        status = "actionable"
    elif relevant and all(item["terminal"] for item in relevant):
        status = "terminal"
    else:
        status = "direct"
    resources = [resource for item in relevant for resource in item["resources"]]
    procedures = [procedure for item in relevant for procedure in item["procedures"]]
    resources = list({canonical_serialize(item): item for item in resources}.values())
    procedures = list({canonical_serialize(item): item for item in procedures}.values())
    context = {item["owner"]: item["facts"] for item in relevant if item["facts"]}
    answer = {
        "input_revision": input_revision,
        "status": status,
        "primary_action": primary_action,
        "decision_request": decision_request,
        "blockers": blockers,
        "claim_boundary": {"allowed": allowed, "blocked": blocked},
        "relevant_owners": owners,
        "context": context,
        "resources": resources,
        "procedures": procedures,
    }
    return {"kind": KINDS["decision"], "decision_id": "operating-decision:" + _digest(answer).removeprefix("sha256:")[:16], **answer}


def select_decision_detail(decision: Mapping[str, Any], fields: Iterable[str]) -> dict[str, Any]:
    selected = {field: decision[field] for field in fields if field in decision}
    return {
        "kind": KINDS["decision_view"],
        "decision_id": decision.get("decision_id"),
        "input_revision": decision.get("input_revision"),
        "authoritative": False,
        "values": selected,
    }
'''


JAVASCRIPT_TEMPLATE = """// Generated by scripts/generate_contracts.py from contracts/semantic-ir.json. Do not edit.
import { createHash } from "node:crypto";

export const IR = __IR__;
export const BUNDLED_SKILLS = __SKILLS__;
const kinds = IR.kinds;
const operationContracts = new Map(IR.operations.map((operation) => [operation.id, operation]));

export function bundledSkill(name) {
  const skill = BUNDLED_SKILLS[name];
  if (!skill) throw new Error(`unknown bundled skill: ${name}`);
  return { ...skill };
}

export function operationContract(operationId) {
  const contract = operationContracts.get(operationId);
  if (!contract) throw new Error(`unknown generated operation contract: ${operationId}`);
  return { ...contract };
}

export function admitModules(modules) {
  const admitted = [...modules].sort((left, right) => left.name.localeCompare(right.name));
  const names = admitted.map((module) => module.name);
  if (names.some((name) => !/^[A-Za-z0-9_.-]+$/.test(name)) || new Set(names).size !== names.length) throw new Error("module names must be canonical, non-empty, and unique");
  const incompatible = admitted.filter((module) => String(module.api_version || "1.0").split(".", 1)[0] !== "1").map((module) => module.name);
  if (incompatible.length) throw new Error(`incompatible module API: ${incompatible.join(", ")}; upgrade agentic-workspace or use a compatible 1.x module`);
  const supported = new Set(IR.module.capabilities);
  const unsupported = admitted.flatMap((module) => module.required_capabilities || []).filter((capability) => !supported.has(capability)).sort();
  if (unsupported.length) throw new Error(`unsupported required module semantics: ${[...new Set(unsupported)].join(", ")}; upgrade agentic-workspace or remove the required capability`);
  const owners = new Map();
  for (const module of admitted) for (const domain of module.owns || []) {
    if (!domain) throw new Error(`module ${module.name} declared an empty owned domain`);
    if (owners.has(domain)) throw new Error(`owned domain conflict: ${domain} (${owners.get(domain)}, ${module.name})`);
    owners.set(domain, module.name);
  }
  return admitted;
}

export function moduleContributions(modules, context) {
  const admitted = admitModules(modules);
  const operationOwners = new Map(admitted.flatMap((owner) => (owner.operations || []).map((operation) => [operation.operation_id, [owner.name, operation]])));
  return admitted.flatMap((module) => {
    const contributed = module.contribute(context);
    if (contributed == null) return [];
    if (contributed && typeof contributed.then === "function") throw new Error("module contribution must be synchronous");
    if (contributed.owner != null && contributed.owner !== module.name) throw new Error(`module ${module.name} attempted to contribute for another owner`);
    const payload = { ...contributed, owner: module.name, resources: [...(module.resources || []), ...(contributed.resources || [])], procedures: [...(module.procedures || []), ...(contributed.procedures || [])] };
    const operations = new Map((module.operations || []).map((operation) => [operation.operation_id, operation]));
    payload.actions = (payload.actions || []).map((action) => {
      let operation = operations.get(action.operation_id);
      let sourceOwner = module.name;
      if (!operation) {
        const target = operationOwners.get(action.operation_id);
        if (!target || !(target[1].accepted_handoffs || []).includes(module.name)) throw new Error(`module ${module.name} proposed an operation it does not own: ${action.operation_id || ""}`);
        [sourceOwner, operation] = target;
      }
      if (JSON.stringify(action.effects || []) !== JSON.stringify(operation.effects)) throw new Error(`module ${module.name} action effects differ from its operation contract`);
      return { ...action, source_owner: sourceOwner, ...(sourceOwner !== module.name ? { handoff_source: module.name } : {}) };
    });
    for (const decision of payload.decisions || []) {
      const operation = operations.get(decision.response_operation_id);
      if (!operation) throw new Error(`module ${module.name} decision response is not admitted by an owned operation: ${decision.response_operation_id || ""}`);
      if (JSON.stringify(decision.effects || []) !== JSON.stringify(operation.effects)) throw new Error(`module ${module.name} decision effects differ from its response operation contract`);
    }
    const ownedClaims = new Set(module.claims || []);
    if ((payload.claims?.allowed || []).some((claim) => !ownedClaims.has(claim))) throw new Error(`module ${module.name} attempted to allow an unowned claim`);
    return [payload];
  });
}

function canonical(value) {
  if (Array.isArray(value)) return value.map(canonical);
  if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).map(([key, item]) => [key.normalize("NFC"), canonical(item)]).sort(([left], [right]) => left < right ? -1 : left > right ? 1 : 0));
  if (typeof value === "string") return value.normalize("NFC");
  if (typeof value === "number" && !Number.isSafeInteger(value)) throw new Error("canonical semantic numbers must be integers");
  if (value === null || typeof value === "boolean" || typeof value === "number") return value;
  throw new Error(`unsupported canonical semantic value: ${typeof value}`);
}

export function canonicalSerialize(value) {
  return JSON.stringify(canonical(value)).replace(/[\\u007f-\\uffff]/g, (character) => `\\\\u${character.charCodeAt(0).toString(16).padStart(4, "0")}`);
}

export function semanticDigest(value) {
  return "sha256:" + createHash("sha256").update(canonicalSerialize(value), "utf8").digest("hex");
}

export function correctionRevision(correction) {
  return semanticDigest({ correction_id: correction.correction_id, statement: correction.statement, subject: correction.subject || {}, applicability: correction.applicability || {}, provenance: correction.provenance || {}, future_usefulness: correction.future_usefulness, existing_owner: correction.existing_owner || {}, deterministic_owner_failure: correction.deterministic_owner_failure || {} });
}

export function validateCorrectionAdmission(kind, args, current = {}) {
  const correction = args.correction || {};
  if (correctionRevision(correction) !== args.correction_revision || correction.provenance?.authority !== "human") return false;
  if (kind === "memory") return !correction.existing_owner && !correction.deterministic_owner_failure && correction.future_usefulness !== "do-not-retain" && (correction.future_usefulness === "retain" || !!correction.applicability?.task_terms?.length || !!correction.applicability?.paths?.length || !!correction.applicability?.dependency_revision) && current.state_revision === args.expected_state_revision;
  const evidence = kind === "planning" ? correction.deterministic_owner_failure : correction.existing_owner;
  const owner = kind === "planning" ? String(current.owner || "") : kind;
  const subjectKind = owner === "repository" ? "repository-rule" : owner === "verification" ? "verification-route" : owner === "assignment" ? (args.owner_ref === "policy" ? "delegation-policy" : "delegation-evidence") : "";
  return !!subjectKind && evidence?.owner === owner && evidence.ref === args.owner_ref && evidence.revision === args.owner_revision && current.owner_ref === args.owner_ref && current.owner_revision === args.owner_revision && correction.subject?.kind === subjectKind && correction.subject?.id === args.owner_ref && (kind !== "planning" || current.state_revision === args.expected_state_revision);
}

export function createTrustedCorrectionIngress({ transport, principal }) {
  if (!transport || !principal) throw new Error("trusted correction ingress requires transport and principal");
  const pending = new Map();
  const completed = new Set();
  const observe = (value) => {
    if (!value?.correction_id || !value?.statement || !value?.subject || typeof value.subject !== "object") throw new Error("a correction requires stable identity, statement, and subject");
    const futureUsefulness = value.future_usefulness || "unspecified";
    if (!["retain", "do-not-retain", "unspecified"].includes(futureUsefulness)) throw new Error("future_usefulness must be retain, do-not-retain, or unspecified");
    const correction = { correction_id: value.correction_id, statement: value.statement, subject: value.subject, applicability: value.applicability || {}, provenance: { authority: "human", transport, principal }, future_usefulness: futureUsefulness, existing_owner: value.existing_owner || null, deterministic_owner_failure: value.deterministic_owner_failure || null };
    correction.revision = correctionRevision(correction);
    const previous = pending.get(correction.correction_id);
    if (previous && canonicalSerialize(previous) !== canonicalSerialize(correction)) throw new Error("correction identity was already admitted with different content");
    if (!completed.has(correction.correction_id)) pending.set(correction.correction_id, correction);
    return correction;
  };
  const complete = (correctionId, revision) => {
    const correction = pending.get(correctionId);
    if (!correction || correction.revision !== revision) throw new Error("cannot complete a stale correction");
    pending.delete(correctionId);
    completed.add(correctionId);
  };
  const disposition = (args) => {
    const correction = pending.get(args.correction_id);
    if (!correction || correction.revision !== args.correction_revision || correction.future_usefulness !== "do-not-retain") return { status: "rejected", effects: [], value: { reason: "owner-operation-required" } };
    complete(correction.correction_id, correction.revision);
    return { status: "applied", effects: ["correction-disposition"], value: { correction_revision: correction.revision, disposition: "no-new-durable-record" } };
  };
  const chooseRetention = (args) => {
    const correction = pending.get(args.correction_id);
    if (!correction || correction.revision !== args.correction_revision) return { status: "rejected", effects: [], value: { reason: "stale-correction" } };
    const futureUsefulness = args.answer === "retain" ? "retain" : "do-not-retain";
    const resolved = { ...correction, future_usefulness: futureUsefulness };
    resolved.revision = correctionRevision(resolved);
    pending.set(correction.correction_id, resolved);
    return { status: "applied", effects: ["correction-disposition"], value: { correction_id: correction.correction_id, previous_revision: correction.revision, correction_revision: resolved.revision, future_usefulness: futureUsefulness } };
  };
  const handoff_complete = (operationId, args, outcome) => {
    if (!["memory.accept-correction", "planning.accept-correction-failure", "repository.accept-correction", "verification.accept-correction", "assignment.accept-correction"].includes(operationId)) return;
    const correction = pending.get(args.correction?.correction_id);
    if (correction && correction.revision === args.correction_revision && outcome.value?.correction_revision === correction.revision) complete(correction.correction_id, correction.revision);
  };
  const module = () => ({
    name: "correction",
    api_version: "1.0",
    required_capabilities: ["operation/owner-handoff"],
    owns: ["correction-custody"],
    operations: [
      { operation_id: "correction.disposition", input_schema: operationContract("correction.disposition").input, effects: ["correction-disposition"], handler: disposition },
      { operation_id: "correction.choose-retention", input_schema: operationContract("correction.choose-retention").input, effects: ["correction-disposition"], handler: chooseRetention }
    ],
    handoff_complete,
    contribute: (context) => {
      if (!pending.size) return null;
      const correction = [...pending.values()].sort((left, right) => left.correction_id.localeCompare(right.correction_id))[0];
      let dispositionName, owner, operation_id, effects, actionArgs;
      const payload = Object.fromEntries(Object.entries(correction).filter(([key]) => key !== "revision"));
      const applicability = correction.applicability || {};
      if (correction.future_usefulness === "unspecified" && !correction.existing_owner && !correction.deterministic_owner_failure && !applicability.task_terms?.length && !applicability.paths?.length && !applicability.dependency_revision) return { revision: correction.revision, facts: { id: correction.correction_id, subject: correction.subject, provenance: correction.provenance, future_usefulness: "unresolved" }, decisions: [{ id: `correction-retention:${correction.correction_id}`, detail_revision: correction.revision, question: "Should this correction be retained for future decisions?", authority: "human", response_operation_id: "correction.choose-retention", effects: ["correction-disposition"], choices: [{ id: "retain", label: "Retain" }, { id: "no-new-durable-record", label: "Do not retain" }] }] };
      if (correction.existing_owner) { dispositionName = "already-owned"; owner = String(correction.existing_owner.owner || ""); operation_id = ({ repository: "repository.accept-correction", verification: "verification.accept-correction", assignment: "assignment.accept-correction" })[owner]; if (!operation_id) return { revision: correction.revision, facts: { id: correction.correction_id, owner }, blockers: [{ code: "unsupported-correction-owner", message: `the named correction owner has no admitted correction operation: ${owner}`, owner: owner || "correction" }] }; effects = []; actionArgs = { target: String(context.target || "."), correction: payload, correction_revision: correction.revision, owner_ref: String(correction.existing_owner.ref || ""), owner_revision: String(correction.existing_owner.revision || "") }; }
      else if (correction.deterministic_owner_failure) { dispositionName = "owner-repair"; owner = "planning"; operation_id = "planning.accept-correction-failure"; effects = ["planning-state"]; actionArgs = { target: String(context.target || "."), correction: payload, correction_revision: correction.revision, owner_ref: String(correction.deterministic_owner_failure.ref || ""), owner_revision: String(correction.deterministic_owner_failure.revision || ""), expected_state_revision: String(context.owner_revisions?.planning || "absent") }; }
      else if (correction.future_usefulness === "do-not-retain") { dispositionName = "no-new-durable-record"; owner = "correction"; operation_id = "correction.disposition"; effects = ["correction-disposition"]; actionArgs = { target: String(context.target || "."), correction_id: correction.correction_id, correction_revision: correction.revision, disposition: dispositionName, owner, owner_revision: "" }; }
      else { dispositionName = "memory"; owner = "memory"; operation_id = "memory.accept-correction"; effects = ["memory-state"]; actionArgs = { target: String(context.target || "."), correction: payload, correction_revision: correction.revision, expected_state_revision: String(context.owner_revisions?.memory || "absent") }; }
      return { revision: correction.revision, facts: { id: correction.correction_id, subject: correction.subject, applicability: correction.applicability, provenance: correction.provenance, future_usefulness: correction.future_usefulness, disposition: dispositionName, owner, owner_revision: actionArgs.owner_revision || actionArgs.expected_state_revision || "" }, actions: [{ operation_id, arguments: actionArgs, effects, priority: 100 }] };
    }
  });
  return { observe, complete, module };
}

export function createRepositoryConfigurationOwner({ rules, pathExists = () => false, sharedAnswers = {}, localAnswers = {}, writeAnswer = null }) {
  const currentRules = () => typeof rules === "function" ? rules() : rules;
  const currentAnswers = () => ({ ...sharedAnswers, ...localAnswers });
  const applicable = (rule, context) => {
    const applies = rule.applies || {};
    const task = String(context.task || "").toLowerCase();
    const changed = context.changed_paths || [];
    return (!applies.task_terms?.length && !applies.paths?.length) || (applies.task_terms || []).some((term) => task.includes(String(term).toLowerCase())) || (applies.paths || []).some((pattern) => changed.some((path) => String(path) === String(pattern)));
  };
  const inferred = (decision, facts) => {
    const matches = (decision.infer || []).filter((candidate) => {
      const when = candidate.when || {};
      const choices = new Set((decision.choices || []).map((choice) => String(choice.id)));
      if (!candidate.answer || !choices.has(String(candidate.answer))) throw new Error("invalid inferred configuration answer");
      if (when.path_exists) {
        const path = String(when.path_exists);
        if (path.startsWith("/") || /^[A-Za-z]:/.test(path) || path.replaceAll("\\\\", "/").split("/").some((part) => !part || part === "." || part === "..")) throw new Error("configuration inference path must be canonical and relative");
        return pathExists(path);
      }
      if (when.fact_equals) return facts[when.fact_equals.key] === when.fact_equals.value;
      throw new Error("configuration inference requires one strong path_exists or fact_equals condition");
    }).map((candidate) => String(candidate.answer));
    if (new Set(matches).size > 1) throw new Error("conflicting current configuration inferences");
    return matches[0] || null;
  };
  const contribute = (context) => {
    const active = currentRules().filter((rule) => applicable(rule, context));
    if (!active.length) return null;
    const facts = {};
    const conflicts = [];
    for (const rule of active) for (const [key, value] of Object.entries(rule.facts || {})) { if (key in facts && canonicalSerialize(facts[key]) !== canonicalSerialize(value)) conflicts.push(key); facts[key] = value; }
    const actions = [], decisions = [];
    for (const rule of active) {
      const decision = rule.decision;
      if (!decision) continue;
      const answer = currentAnswers()[rule.id];
      if (answer?.rule_revision === rule.revision) {
        if (answer.disposition === "deferred" && context.configuration?.resume === true) decisions.push({ id: rule.id, detail_revision: rule.revision, question: decision.question, authority: decision.authority || "maintainer", response_operation_id: "repository.answer", effects: ["repository-configuration"], choices: [...(decision.choices || []), { id: "defer", label: "Defer for now" }], allow_open: decision.allow_open === true });
        else facts[`configuration:${rule.id}`] = answer.disposition === "deferred" ? { status: "deferred", rule_revision: rule.revision } : answer.answer;
        continue;
      }
      const inferredAnswer = inferred(decision, facts);
      if (inferredAnswer) actions.push({ operation_id: "repository.answer", arguments: { target: String(context.target || "."), rule_id: rule.id, rule_revision: rule.revision, answer: inferredAnswer, scope: decision.scope || "shared" }, effects: ["repository-configuration"], authority: "repository-inference", priority: 1000 - actions.length });
      else decisions.push({ id: rule.id, detail_revision: rule.revision, question: decision.question, authority: decision.authority || "maintainer", response_operation_id: "repository.answer", effects: ["repository-configuration"], choices: [...(decision.choices || []), ...(decision.required === false ? [{ id: "defer", label: "Defer for now" }] : [])], allow_open: decision.allow_open === true });
    }
    const blockers = conflicts.length ? [{ code: "repository-control-conflict", message: "applicable repository controls disagree on hard facts", owner: "repository" }] : [];
    return { revision: semanticDigest({ rules: active.map((rule) => [rule.id, rule.revision]), answers: currentAnswers(), configuration: context.configuration || null }), facts, actions: blockers.length ? [] : actions.slice(0, 1), decisions: blockers.length || actions.length ? [] : decisions.slice(0, 1), blockers, terminal: !blockers.length && !actions.length && !decisions.length };
  };
  const answer = async (args) => {
    const rule = currentRules().find((item) => item.id === args.rule_id);
    const decision = rule?.decision || {};
    if (!rule || rule.revision !== args.rule_revision) return { status: "rejected", effects: [], value: { reason: "stale-repository-rule" } };
    if ((decision.scope || "shared") !== args.scope || (args.answer === "defer" && decision.required !== false)) return { status: "rejected", effects: [], value: { reason: "configuration-answer-not-admitted" } };
    const choices = new Set((decision.choices || []).map((choice) => choice.id));
    if (args.answer !== "defer" && choices.size && !choices.has(args.answer) && decision.allow_open !== true) return { status: "rejected", effects: [], value: { reason: "configuration-answer-not-admitted" } };
    const value = { rule_revision: rule.revision, answer: args.answer, scope: args.scope, disposition: args.answer === "defer" ? "deferred" : "configured" };
    if (writeAnswer) await writeAnswer(args.scope, rule.id, value);
    (args.scope === "local" ? localAnswers : sharedAnswers)[rule.id] = value;
    return { status: "applied", effects: ["repository-configuration"], value };
  };
  return { name: "repository", owns: ["repository-configuration"], operations: [{ operation_id: "repository.answer", input_schema: operationContract("repository.answer").input, effects: ["repository-configuration"], handler: answer }], contribute };
}

const hash = semanticDigest;

export function ownerConclusionIdentity(owner, revision, dependencies = {}) {
  if (!owner || !revision) throw new Error("owner conclusion identity requires owner and revision");
  return semanticDigest({ owner, revision, dependencies });
}

function strings(value, field) {
  if (value == null) return [];
  if (!Array.isArray(value) || value.some((item) => typeof item !== "string" || !item)) throw new Error(`${field} must be a list of non-empty strings`);
  return [...value];
}

function references(value, owner, field) {
  if (value == null) return [];
  if (!Array.isArray(value) || value.some((item) => !item || typeof item !== "object" || Array.isArray(item))) throw new Error(`${owner}.${field} must be a list of objects`);
  return value.map((item, index) => {
    if (!item.id || !item.revision || !item.locator) throw new Error(`${owner}.${field}[${index}] requires id, revision, and locator`);
    return { id: String(item.id), owner, revision: String(item.revision), locator: String(item.locator), summary: String(item.summary || ""), authority: field === "procedures" ? "reference-only" : "read-only" };
  });
}

export function normalizeContribution(value) {
  const owner = String(value.owner || "").trim();
  const revision = String(value.revision || "").trim();
  if (!owner || !revision) throw new Error("a contribution requires owner and revision");
  const blockers = value.blockers || [];
  const actions = value.actions || [];
  const decisions = value.decisions || [];
  if (!Array.isArray(blockers) || blockers.some((item) => !item || typeof item !== "object" || Array.isArray(item))) throw new Error(`${owner}.blockers must be a list of objects`);
  if (!Array.isArray(actions) || actions.some((item) => !item || typeof item !== "object" || Array.isArray(item))) throw new Error(`${owner}.actions must be a list of objects`);
  if (!Array.isArray(decisions) || decisions.some((item) => !item || typeof item !== "object" || Array.isArray(item))) throw new Error(`${owner}.decisions must be a list of objects`);
  const normalizedActions = actions.map((item, index) => {
    const operationId = String(item.operation_id || "").trim();
    if (!operationId) throw new Error(`${owner}.actions[${index}].operation_id is required`);
    if (!item.arguments || typeof item.arguments !== "object" || Array.isArray(item.arguments)) throw new Error(`${owner}.actions[${index}].arguments must be an object`);
    if (!Number.isInteger(item.priority || 0)) throw new Error(`${owner}.actions[${index}].priority must be an integer`);
    return { operation_id: operationId, arguments: item.arguments || {}, effects: strings(item.effects, `${owner}.actions[${index}].effects`), authority: String(item.authority || owner), source_owner: String(item.source_owner || owner), handoff_source: String(item.handoff_source || ""), priority: item.priority || 0 };
  });
  const normalizedBlockers = blockers.map((item, index) => {
    if (!item.code || !item.message) throw new Error(`${owner}.blockers[${index}] requires code and message`);
    const blocker = { code: String(item.code), message: String(item.message), owner: String(item.owner || owner) };
    if (item.recovery) blocker.recovery = String(item.recovery);
    return blocker;
  });
  const normalizedDecisions = decisions.map((item, index) => {
    const id = String(item.id || "").trim();
    const question = String(item.question || "").trim();
    const authority = String(item.authority || "").trim();
    const responseOperationId = String(item.response_operation_id || "").trim();
    const choices = item.choices || [];
    const allowOpen = item.allow_open === true;
    if (!id || !question || !authority || !responseOperationId) throw new Error(`${owner}.decisions[${index}] requires id, question, authority, and response_operation_id`);
    if (!Array.isArray(choices) || choices.some((choice) => !choice || typeof choice !== "object" || Array.isArray(choice))) throw new Error(`${owner}.decisions[${index}].choices must be a list of objects`);
    const normalizedChoices = choices.map((choice, choiceIndex) => {
      const choiceId = String(choice.id || "").trim();
      const label = String(choice.label || "").trim();
      if (!choiceId || !label) throw new Error(`${owner}.decisions[${index}].choices[${choiceIndex}] requires id and label`);
      return { id: choiceId, label };
    });
    if (!normalizedChoices.length && !allowOpen) throw new Error(`${owner}.decisions[${index}] requires finite choices or allow_open`);
    return { id, owner, revision, detail_revision: String(item.detail_revision || revision), question, authority, response_operation_id: responseOperationId, effects: strings(item.effects, `${owner}.decisions[${index}].effects`), choices: normalizedChoices, allow_open: allowOpen };
  });
  const claims = value.claims || {};
  const facts = value.facts || {};
  return { owner, revision, relevant: value.relevant !== false, facts, resources: references(value.resources, owner, "resources"), procedures: references(value.procedures, owner, "procedures"), decisions: normalizedDecisions, blockers: normalizedBlockers, actions: normalizedActions, claims: { allowed: strings(claims.allowed, `${owner}.claims.allowed`), blocked: strings(claims.blocked, `${owner}.claims.blocked`) }, terminal: value.terminal === true };
}

export function compileSourceDecision(contributions, intent = {}) {
  const relevant = contributions.map(normalizeContribution).filter((item) => item.relevant).sort((a, b) => a.owner.localeCompare(b.owner));
  const owners = relevant.map((item) => item.owner);
  if (new Set(owners).size !== owners.length) throw new Error("each source owner may contribute at most once");
  const inputRevision = hash({ intent, sources: relevant });
  const blockers = relevant.flatMap((item) => item.blockers);
  const decisions = relevant.flatMap((item) => item.decisions);
  const actions = relevant.flatMap((item) => item.actions.map((action) => [item.owner, action]));
  actions.sort((a, b) => b[1].priority - a[1].priority || a[0].localeCompare(b[0]) || a[1].operation_id.localeCompare(b[1].operation_id));
  let primaryAction = null;
  let decisionRequest = null;
  if (!blockers.length && decisions.length === 1) decisionRequest = decisions[0];
  else if (!blockers.length && decisions.length > 1) blockers.push({ code: "ambiguous-decision", message: "multiple source owners require a current human/domain decision", owner: "operating-decision", recovery: "reconcile the competing decision owners" });
  if (!blockers.length && !decisionRequest && actions.length) {
    const tied = actions.filter((pair) => pair[1].priority === actions[0][1].priority);
    if (tied.length > 1) blockers.push({ code: "ambiguous-action", message: "multiple source owners proposed equally authoritative actions", owner: "operating-decision", recovery: "reconcile the competing source owners" });
    else {
      const [owner, action] = actions[0];
      primaryAction = { kind: kinds.invocation, operation_id: action.operation_id, arguments: action.arguments, intent, effects: action.effects, authority: action.authority, source_owner: action.source_owner, ...(action.handoff_source ? { handoff_source: action.handoff_source } : {}), expected_input_revision: inputRevision, idempotency_key: hash({ operation_id: action.operation_id, arguments: action.arguments, input_revision: inputRevision }) };
    }
  }
  const blocked = [...new Set(relevant.flatMap((item) => item.claims.blocked))].sort();
  const allowed = [...new Set(relevant.flatMap((item) => item.claims.allowed))].filter((claim) => !blocked.includes(claim)).sort();
  if (blockers.length > 1) {
    const causes = blockers.map((item) => `${item.owner}:${item.code}`).sort();
    blockers.splice(0, blockers.length, { code: "multiple-blockers", message: "multiple current blockers require source-owner reconciliation", owner: "operating-decision", recovery: "reconcile: " + causes.join(", ") });
  }
  const status = blockers.length ? "blocked" : decisionRequest ? "decision" : primaryAction ? "actionable" : relevant.length && relevant.every((item) => item.terminal) ? "terminal" : "direct";
  if (blockers.length) { primaryAction = null; decisionRequest = null; }
  const resources = [...new Map(relevant.flatMap((item) => item.resources).map((item) => [canonicalSerialize(item), item])).values()];
  const procedures = [...new Map(relevant.flatMap((item) => item.procedures).map((item) => [canonicalSerialize(item), item])).values()];
  const context = Object.fromEntries(relevant.filter((item) => Object.keys(item.facts).length).map((item) => [item.owner, item.facts]));
  const answer = { input_revision: inputRevision, status, primary_action: primaryAction, decision_request: decisionRequest, blockers, claim_boundary: { allowed, blocked }, relevant_owners: owners, context, resources, procedures };
  return { kind: kinds.decision, decision_id: "operating-decision:" + hash(answer).slice(7, 23), ...answer };
}

function validate(schema, value, field = "arguments") {
  if (schema.const !== undefined && value !== schema.const) throw new Error(`${field} must equal ${schema.const}`);
  if (schema.enum && !schema.enum.includes(value)) throw new Error(`${field} must be one of the declared values`);
  if (schema.type === "object") {
    if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${field} must be an object`);
    for (const required of schema.required || []) if (!(required in value)) throw new Error(`${field}.${required} is required`);
    if (schema.additionalProperties === false) for (const key of Object.keys(value)) if (!(key in (schema.properties || {}))) throw new Error(`${field}.${key} is not allowed`);
    for (const [key, child] of Object.entries(schema.properties || {})) if (key in value) validate(child, value[key], `${field}.${key}`);
  } else if (schema.type === "string") {
    if (typeof value !== "string" || (schema.minLength && value.length < schema.minLength)) throw new Error(`${field} must be a string`);
  } else if (schema.type === "array") {
    if (!Array.isArray(value) || (schema.minItems && value.length < schema.minItems)) throw new Error(`${field} must be an array`);
    if (schema.items) value.forEach((item, index) => validate(schema.items, item, `${field}[${index}]`));
  }
}

export class OperationDispatcher {
  constructor({ receiptLoader = null, receiptWriter = null, commitCoordinator = null, handoffNotifier = null } = {}) {
    this.operations = new Map();
    this.receipts = new Map();
    this.receiptLoader = receiptLoader;
    this.receiptWriter = receiptWriter;
    this.commitCoordinator = commitCoordinator;
    this.handoffNotifier = handoffNotifier;
  }
  register(operation) {
    if (!operation.operation_id || this.operations.has(operation.operation_id)) throw new Error(`invalid or duplicate operation: ${operation.operation_id || ""}`);
    this.operations.set(operation.operation_id, operation);
  }
  async invoke(invocation, resolveDecision) {
    if (invocation.kind !== kinds.invocation) throw new Error("unsupported invocation kind");
    const operation = this.operations.get(invocation.operation_id);
    if (!operation) throw new Error(`unknown operation: ${invocation.operation_id || ""}`);
    validate(operation.input_schema, invocation.arguments);
    if (JSON.stringify(invocation.effects || []) !== JSON.stringify(operation.effects)) throw new Error("invocation effects do not match the operation contract");
    if (!invocation.idempotency_key) throw new Error("idempotency_key is required");
    const request = { operation_id: invocation.operation_id, arguments: invocation.arguments, revision: invocation.expected_input_revision, source_owner: invocation.source_owner, ...(invocation.handoff_source != null ? { handoff_source: invocation.handoff_source } : {}), decision_response: invocation.decision_response || null };
    const previous = this.receipts.get(invocation.idempotency_key) || (this.receiptLoader ? await this.receiptLoader(invocation.idempotency_key) : null);
    if (previous) {
      if (JSON.stringify(previous.request) !== JSON.stringify(request)) throw new Error("idempotency key was already used for another invocation");
      return previous.result;
    }
    const current = await resolveDecision();
    const currentOperationId = current.primary_action?.operation_id || current.decision_request?.response_operation_id;
    if (!invocation.expected_input_revision || invocation.expected_input_revision !== current.input_revision || currentOperationId !== invocation.operation_id) throw new Error("source state changed; resolve a fresh operating decision");
    const currentOwner = current.primary_action?.source_owner || current.decision_request?.owner;
    if (invocation.source_owner !== currentOwner) throw new Error("invocation source_owner does not match the current source owner");
    if (invocation.handoff_source !== current.primary_action?.handoff_source) throw new Error("invocation handoff_source does not match the current handoff source");
    if (current.decision_request?.response_operation_id === invocation.operation_id) {
      const response = invocation.decision_response;
      const expected = current.decision_request;
      if (!response) throw new Error("bounded decision invocation requires decision_response");
      if (response.id !== expected.id || response.owner !== expected.owner || response.revision !== expected.revision || response.authority !== expected.authority) throw new Error("bounded decision response owner, revision, or authority is stale");
      if ("answer" in invocation.arguments && invocation.arguments.answer !== response.answer) throw new Error("typed decision answer differs from decision_response");
      const choiceIds = new Set((expected.choices || []).map((choice) => choice.id));
      if (choiceIds.size && !choiceIds.has(response.answer) && expected.allow_open !== true) throw new Error("bounded decision answer is not one of the current choices");
      if (!choiceIds.size && (expected.allow_open !== true || typeof response.answer !== "string" || !response.answer)) throw new Error("bounded open judgment requires a non-empty answer");
    }
    if (operation.effects.length && !this.commitCoordinator) throw new Error("effectful operations require a durable commit coordinator");
    const execute = () => operation.handler({ ...invocation.arguments });
    const recover = operation.recover ? () => operation.recover({ ...invocation.arguments }) : null;
    const raw = this.commitCoordinator
      ? await this.commitCoordinator.run({ key: invocation.idempotency_key, request, execute, recover })
      : await execute();
    if (!IR.operation.result_statuses.includes(raw.status)) throw new Error("operation result status is invalid");
    if (!Array.isArray(raw.effects) || raw.effects.some((effect) => !operation.effects.includes(effect))) throw new Error("operation result widened its declared effects");
    if (["applied", "unchanged"].includes(raw.status) && invocation.handoff_source && this.handoffNotifier) await this.handoffNotifier(invocation.handoff_source, invocation.operation_id, invocation.arguments, raw);
    const result = { kind: kinds.result, operation_id: invocation.operation_id, status: raw.status, effects: raw.effects, value: raw.value ?? null, input_revision: invocation.expected_input_revision, next_decision: await resolveDecision() };
    const receipt = { request, result };
    this.receipts.set(invocation.idempotency_key, receipt);
    if (this.receiptWriter) await this.receiptWriter(invocation.idempotency_key, request, result);
    return result;
  }
}
"""


DECLARATIONS = """// Generated by scripts/generate_contracts.py. Do not edit.
export type Json = null | boolean | number | string | Json[] | { [key: string]: Json };
export interface Contribution { owner: string; revision: string; relevant?: boolean; facts?: Record<string, Json>; resources?: ResourceReference[]; procedures?: ResourceReference[]; decisions?: DecisionRequest[]; blockers?: Record<string, Json>[]; actions?: Record<string, Json>[]; claims?: { allowed?: string[]; blocked?: string[] }; terminal?: boolean; }
export interface ResourceReference { id: string; revision: string; locator: string; summary?: string; }
export interface DecisionRequest { id: string; question: string; authority: string; response_operation_id: string; choices?: { id: string; label: string }[]; allow_open?: boolean; }
export declare const IR: Record<string, Json>;
export interface BundledSkill { name: string; description: string; content: string; }
export declare const BUNDLED_SKILLS: Record<string, BundledSkill>;
export declare function bundledSkill(name: string): BundledSkill;
export declare function canonicalSerialize(value: Json): string;
export declare function semanticDigest(value: Json): string;
export interface TrustedCorrectionIngress { observe(value: Record<string, Json>): Record<string, Json>; complete(correctionId: string, revision: string): void; module(): Module; }
export declare function correctionRevision(correction: Record<string, Json>): string;
export declare function validateCorrectionAdmission(kind: "memory" | "repository" | "verification" | "assignment" | "planning", args: Record<string, Json>, current?: Record<string, Json>): boolean;
export declare function createTrustedCorrectionIngress(options: { transport: string; principal: string }): TrustedCorrectionIngress;
export declare function createRepositoryConfigurationOwner(options: { rules: Record<string, Json>[] | (() => Record<string, Json>[]); pathExists?: (path: string) => boolean; sharedAnswers?: Record<string, Json>; localAnswers?: Record<string, Json>; writeAnswer?: (scope: string, id: string, value: Record<string, Json>) => Promise<void> | void }): Module;
export declare function ownerConclusionIdentity(owner: string, revision: string, dependencies?: Record<string, Json>): string;
export declare function operationContract(operationId: string): Record<string, Json>;
export interface Module { name: string; api_version?: string; required_capabilities?: string[]; owns?: string[]; claims?: string[]; resources?: ResourceReference[]; procedures?: ResourceReference[]; operations?: Operation[]; contribute: (context: Record<string, Json>) => Contribution | null; handoff_complete?: (operationId: string, arguments: Record<string, Json>, outcome: Record<string, Json>) => void; }
export declare function admitModules(modules: Module[]): Module[];
export declare function moduleContributions(modules: Module[], context: Record<string, Json>): Contribution[];
export declare function normalizeContribution(value: Contribution): Record<string, Json>;
export declare function compileSourceDecision(contributions: Contribution[], intent?: Record<string, Json>): Record<string, Json>;
export interface Operation { operation_id: string; input_schema: Record<string, Json>; effects: string[]; accepted_handoffs?: string[]; handler: (arguments: Record<string, Json>) => Promise<Record<string, Json>> | Record<string, Json>; recover?: (arguments: Record<string, Json>) => Promise<Record<string, Json> | null> | Record<string, Json> | null; }
export interface CommitCoordinator { run(context: { key: string; request: Record<string, Json>; execute: () => Promise<Record<string, Json>> | Record<string, Json>; recover: (() => Promise<Record<string, Json> | null> | Record<string, Json> | null) | null }): Promise<Record<string, Json>> | Record<string, Json>; }
export declare class OperationDispatcher { constructor(options?: Record<string, unknown>); register(operation: Operation): void; invoke(invocation: Record<string, Json>, resolveDecision: () => Promise<Record<string, Json>> | Record<string, Json>): Promise<Record<string, Json>>; }
"""


def _write(path: Path, value: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(value.rstrip() + "\n", encoding="utf-8")


def _bundled_skills(root: Path) -> dict[str, dict[str, str]]:
    skills: dict[str, dict[str, str]] = {}
    for path in sorted((root / "contracts" / "skills").glob("*/SKILL.md")):
        content = path.read_text(encoding="utf-8")
        frontmatter = content.split("---", 2)
        fields = {
            key.strip(): value.strip()
            for line in frontmatter[1].splitlines()
            if ":" in line
            for key, value in [line.split(":", 1)]
        }
        name = fields.get("name", "")
        description = fields.get("description", "")
        if not name or name != path.parent.name or not description:
            raise ValueError(f"invalid bundled skill metadata: {path}")
        skills[name] = {"name": name, "description": description, "content": content}
    return skills


def generate(root: Path, *, output_root: Path | None = None) -> None:
    destination = output_root or root
    ir = json.loads((root / "contracts" / "semantic-ir.json").read_text(encoding="utf-8"))
    skills = _bundled_skills(root)
    pyproject_path = root / "pyproject.toml"
    if pyproject_path.is_file():
        python_version = tomllib.loads(pyproject_path.read_text(encoding="utf-8"))["project"]["version"]
        if python_version != ir["package_version"]:
            raise ValueError("Python and semantic IR package versions must match")
    compact = json.dumps(ir, sort_keys=True, separators=(",", ":"))
    pretty = json.dumps(ir, indent=2, sort_keys=True)
    python_output = destination / "src" / "agentic_workspace" / "generated_semantics.py"
    _write(
        python_output,
        PYTHON_TEMPLATE.replace("__IR__", pprint.pformat(ir, sort_dicts=True, width=120)).replace(
            "__SKILLS__", pprint.pformat(skills, sort_dicts=True, width=120)
        ),
    )
    ruff = shutil.which("ruff")
    if ruff is not None:
        subprocess.run([ruff, "format", "--quiet", str(python_output)], check=True)
    _write(
        destination / "typescript" / "dist" / "index.js",
        JAVASCRIPT_TEMPLATE.replace("__IR__", compact).replace(
            "__SKILLS__", json.dumps(skills, sort_keys=True, separators=(",", ":"))
        ),
    )
    _write(destination / "typescript" / "dist" / "index.d.ts", DECLARATIONS)
    package = {
        "name": "@rickardvh/agentic-workspace",
        "version": ir["package_version"],
        "description": "Generated TypeScript/JavaScript projection of the Agentic Workspace semantic contract.",
        "type": "module",
        "main": "dist/index.js",
        "types": "dist/index.d.ts",
        "exports": {".": {"types": "./dist/index.d.ts", "import": "./dist/index.js"}},
        "files": ["dist", "semantic-ir.json", "skills"],
        "license": "MIT",
        "repository": {"type": "git", "url": "https://github.com/rickardvh/agentic-workspace.git"},
    }
    _write(destination / "typescript" / "package.json", json.dumps(package, indent=2, sort_keys=True))
    _write(destination / "typescript" / "semantic-ir.json", pretty)
    _write(destination / "src" / "agentic_workspace" / "semantic-ir.json", pretty)
    for name, skill in skills.items():
        _write(destination / "src" / "agentic_workspace" / "skills" / name / "SKILL.md", skill["content"])
        _write(destination / "typescript" / "skills" / name / "SKILL.md", skill["content"])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--output-root", type=Path)
    args = parser.parse_args()
    generate(args.root.resolve(), output_root=args.output_root.resolve() if args.output_root else None)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
